// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.sirius.Begin = (function(_super) {
    var $a;

    __extends(Begin, _super);

    /* $a = alias for sirius namespace
    */


    function Begin() {
      return Begin.__super__.constructor.apply(this, arguments);
    }

    $a = window.sirius;

    Begin.from_xml1 = function(xml, object_with_id) {
      var deferred, fn, obj, _i, _len;
      deferred = [];
      obj = this.from_xml2(xml, deferred, object_with_id);
      for (_i = 0, _len = deferred.length; _i < _len; _i++) {
        fn = deferred[_i];
        fn();
      }
      return obj;
    };

    Begin.from_xml2 = function(xml, deferred, object_with_id) {
      var node_id, obj;
      if (!(xml != null) || xml.length === 0) {
        return null;
      }
      obj = new window.sirius.Begin();
      node_id = $(xml).attr('node_id');
      obj.set('node_id', node_id);
      if (obj.resolve_references) {
        obj.resolve_references(deferred, object_with_id);
      }
      return obj;
    };

    Begin.prototype.to_xml = function(doc) {
      var xml;
      xml = doc.createElement('begin');
      if (this.encode_references) {
        this.encode_references();
      }
      if (this.has('node_id')) {
        xml.setAttribute('node_id', this.get('node_id'));
      }
      return xml;
    };

    Begin.prototype.deep_copy = function() {
      return Begin.from_xml1(this.to_xml(), {});
    };

    Begin.prototype.inspect = function(depth, indent, orig_depth) {
      if (depth == null) {
        depth = 1;
      }
      if (indent == null) {
        indent = false;
      }
      if (orig_depth == null) {
        orig_depth = -1;
      }
      return null;
    };

    Begin.prototype.make_tree = function() {
      return null;
    };

    return Begin;

  })(Backbone.Model);

}).call(this);
