// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.sirius.CapacityProfile = (function(_super) {
    var $a;

    __extends(CapacityProfile, _super);

    /* $a = alias for sirius namespace
    */


    function CapacityProfile() {
      return CapacityProfile.__super__.constructor.apply(this, arguments);
    }

    $a = window.sirius;

    CapacityProfile.from_xml1 = function(xml, object_with_id) {
      var deferred, fn, obj, _i, _len;
      deferred = [];
      obj = this.from_xml2(xml, deferred, object_with_id);
      for (_i = 0, _len = deferred.length; _i < _len; _i++) {
        fn = deferred[_i];
        fn();
      }
      return obj;
    };

    CapacityProfile.from_xml2 = function(xml, deferred, object_with_id) {
      var dt, link_id, obj, start_time;
      if (!(xml != null) || xml.length === 0) {
        return null;
      }
      obj = new window.sirius.CapacityProfile();
      link_id = $(xml).attr('link_id');
      obj.set('link_id', link_id);
      start_time = $(xml).attr('start_time');
      obj.set('start_time', Number(start_time));
      dt = $(xml).attr('dt');
      obj.set('dt', Number(dt));
      obj.set('text', xml.text());
      if (obj.resolve_references) {
        obj.resolve_references(deferred, object_with_id);
      }
      return obj;
    };

    CapacityProfile.prototype.to_xml = function(doc) {
      var xml;
      xml = doc.createElement('capacityProfile');
      if (this.encode_references) {
        this.encode_references();
      }
      if (this.has('link_id')) {
        xml.setAttribute('link_id', this.get('link_id'));
      }
      if (this.has('start_time') && this.start_time !== 0) {
        xml.setAttribute('start_time', this.get('start_time'));
      }
      if (this.has('dt')) {
        xml.setAttribute('dt', this.get('dt'));
      }
      xml.appendChild(doc.createTextNode($a.ArrayText.emit(this.get('text') || [])));
      return xml;
    };

    CapacityProfile.prototype.deep_copy = function() {
      return CapacityProfile.from_xml1(this.to_xml(), {});
    };

    CapacityProfile.prototype.inspect = function(depth, indent, orig_depth) {
      if (depth == null) {
        depth = 1;
      }
      if (indent == null) {
        indent = false;
      }
      if (orig_depth == null) {
        orig_depth = -1;
      }
      return null;
    };

    CapacityProfile.prototype.make_tree = function() {
      return null;
    };

    return CapacityProfile;

  })(Backbone.Model);

}).call(this);
