// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.sirius.Controller = (function(_super) {
    var $a;

    __extends(Controller, _super);

    /* $a = alias for sirius namespace
    */


    function Controller() {
      return Controller.__super__.constructor.apply(this, arguments);
    }

    $a = window.sirius;

    Controller.from_xml1 = function(xml, object_with_id) {
      var deferred, fn, obj, _i, _len;
      deferred = [];
      obj = this.from_xml2(xml, deferred, object_with_id);
      for (_i = 0, _len = deferred.length; _i < _len; _i++) {
        fn = deferred[_i];
        fn();
      }
      return obj;
    };

    Controller.from_xml2 = function(xml, deferred, object_with_id) {
      var PlanList, PlanSequence, display_position, dt, feedbackElements, id, link_position, name, obj, parameters, qcontroller, targetElements, type;
      if (!(xml != null) || xml.length === 0) {
        return null;
      }
      obj = new window.sirius.Controller();
      display_position = xml.children('display_position');
      obj.set('display_position', $a.Display_position.from_xml2(display_position, deferred, object_with_id));
      targetElements = xml.children('targetElements');
      obj.set('targetelements', $a.TargetElements.from_xml2(targetElements, deferred, object_with_id));
      feedbackElements = xml.children('feedbackElements');
      obj.set('feedbackelements', $a.FeedbackElements.from_xml2(feedbackElements, deferred, object_with_id));
      parameters = xml.children('parameters');
      obj.set('parameters', _.reduce(parameters.find("parameter"), function(acc, par_xml) {
        var wrapped_xml;
        wrapped_xml = $(par_xml);
        acc[wrapped_xml.attr('name')] = wrapped_xml.attr('value');
        return acc;
      }, {}));
      qcontroller = xml.children('qcontroller');
      obj.set('qcontroller', $a.Qcontroller.from_xml2(qcontroller, deferred, object_with_id));
      PlanSequence = xml.children('PlanSequence');
      obj.set('plansequence', $a.PlanSequence.from_xml2(PlanSequence, deferred, object_with_id));
      PlanList = xml.children('PlanList');
      obj.set('planlist', $a.PlanList.from_xml2(PlanList, deferred, object_with_id));
      name = $(xml).attr('name');
      obj.set('name', name);
      link_position = $(xml).attr('link_position');
      obj.set('link_position', Number(link_position));
      type = $(xml).attr('type');
      obj.set('type', type);
      id = $(xml).attr('id');
      obj.set('id', id);
      dt = $(xml).attr('dt');
      obj.set('dt', Number(dt));
      if (obj.resolve_references) {
        obj.resolve_references(deferred, object_with_id);
      }
      return obj;
    };

    Controller.prototype.to_xml = function(doc) {
      var parameters_xml, xml;
      xml = doc.createElement('controller');
      if (this.encode_references) {
        this.encode_references();
      }
      if (this.has('display_position')) {
        xml.appendChild(this.get('display_position').to_xml(doc));
      }
      if (this.has('targetelements')) {
        xml.appendChild(this.get('targetelements').to_xml(doc));
      }
      if (this.has('feedbackelements')) {
        xml.appendChild(this.get('feedbackelements').to_xml(doc));
      }
      if (this.has('parameters')) {
        parameters_xml = doc.createElement('parameters');
        _.each(this.get('parameters'), function(par_val, par_name) {
          var parameter_xml;
          parameter_xml = doc.createElement('parameter');
          parameter_xml.setAttribute(par_name, par_val);
          return parameters_xml.appendChild(parameter_xml);
        });
        xml.appendChild(parameters_xml);
      }
      if (this.has('qcontroller')) {
        xml.appendChild(this.get('qcontroller').to_xml(doc));
      }
      if (this.has('plansequence')) {
        xml.appendChild(this.get('plansequence').to_xml(doc));
      }
      if (this.has('planlist')) {
        xml.appendChild(this.get('planlist').to_xml(doc));
      }
      if (this.has('name')) {
        xml.setAttribute('name', this.get('name'));
      }
      if (this.has('link_position')) {
        xml.setAttribute('link_position', this.get('link_position'));
      }
      if (this.has('type')) {
        xml.setAttribute('type', this.get('type'));
      }
      if (this.has('id')) {
        xml.setAttribute('id', this.get('id'));
      }
      if (this.has('dt')) {
        xml.setAttribute('dt', this.get('dt'));
      }
      return xml;
    };

    Controller.prototype.deep_copy = function() {
      return Controller.from_xml1(this.to_xml(), {});
    };

    Controller.prototype.inspect = function(depth, indent, orig_depth) {
      if (depth == null) {
        depth = 1;
      }
      if (indent == null) {
        indent = false;
      }
      if (orig_depth == null) {
        orig_depth = -1;
      }
      return null;
    };

    Controller.prototype.make_tree = function() {
      return null;
    };

    return Controller;

  })(Backbone.Model);

}).call(this);
