// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.sirius.ContextMenuItemView = (function(_super) {

    __extends(ContextMenuItemView, _super);

    function ContextMenuItemView() {
      return ContextMenuItemView.__super__.constructor.apply(this, arguments);
    }

    ContextMenuItemView.prototype.tagName = 'li';

    ContextMenuItemView.prototype.initialize = function(parentId, values) {
      this.parentId = parentId;
      this.template = _.template($('#child-item-menu-template').html());
      if (values.label) {
        this.$el.html(this.template({
          text: values.label
        }));
      }
      if (values.className) {
        this.$el.attr('class', values.className);
      }
      if (values.id) {
        this.$el.attr('id', values.id);
      }
      if (values.event) {
        this.events = {
          click: values.event
        };
      }
      return this.render();
    };

    ContextMenuItemView.prototype.render = function() {
      $("#" + this.parentId).append(this.el);
      return this;
    };

    return ContextMenuItemView;

  })(Backbone.View);

}).call(this);
