// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.sirius.Data_source = (function(_super) {
    var $a;

    __extends(Data_source, _super);

    /* $a = alias for sirius namespace
    */


    function Data_source() {
      return Data_source.__super__.constructor.apply(this, arguments);
    }

    $a = window.sirius;

    Data_source.from_xml1 = function(xml, object_with_id) {
      var deferred, fn, obj, _i, _len;
      deferred = [];
      obj = this.from_xml2(xml, deferred, object_with_id);
      for (_i = 0, _len = deferred.length; _i < _len; _i++) {
        fn = deferred[_i];
        fn();
      }
      return obj;
    };

    Data_source.from_xml2 = function(xml, deferred, object_with_id) {
      var dt, format, obj, url;
      if (!(xml != null) || xml.length === 0) {
        return null;
      }
      obj = new window.sirius.Data_source();
      url = $(xml).attr('url');
      obj.set('url', url);
      dt = $(xml).attr('dt');
      obj.set('dt', Number(dt));
      format = $(xml).attr('format');
      obj.set('format', format);
      if (obj.resolve_references) {
        obj.resolve_references(deferred, object_with_id);
      }
      return obj;
    };

    Data_source.prototype.to_xml = function(doc) {
      var xml;
      xml = doc.createElement('data_source');
      if (this.encode_references) {
        this.encode_references();
      }
      if (this.has('url')) {
        xml.setAttribute('url', this.get('url'));
      }
      if (this.has('dt')) {
        xml.setAttribute('dt', this.get('dt'));
      }
      if (this.has('format')) {
        xml.setAttribute('format', this.get('format'));
      }
      return xml;
    };

    Data_source.prototype.deep_copy = function() {
      return Data_source.from_xml1(this.to_xml(), {});
    };

    Data_source.prototype.inspect = function(depth, indent, orig_depth) {
      if (depth == null) {
        depth = 1;
      }
      if (indent == null) {
        indent = false;
      }
      if (orig_depth == null) {
        orig_depth = -1;
      }
      return null;
    };

    Data_source.prototype.make_tree = function() {
      return null;
    };

    return Data_source;

  })(Backbone.Model);

}).call(this);
