// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.sirius.Data_sources = (function(_super) {
    var $a;

    __extends(Data_sources, _super);

    /* $a = alias for sirius namespace
    */


    function Data_sources() {
      return Data_sources.__super__.constructor.apply(this, arguments);
    }

    $a = window.sirius;

    Data_sources.from_xml1 = function(xml, object_with_id) {
      var deferred, fn, obj, _i, _len;
      deferred = [];
      obj = this.from_xml2(xml, deferred, object_with_id);
      for (_i = 0, _len = deferred.length; _i < _len; _i++) {
        fn = deferred[_i];
        fn();
      }
      return obj;
    };

    Data_sources.from_xml2 = function(xml, deferred, object_with_id) {
      var data_source, obj;
      if (!(xml != null) || xml.length === 0) {
        return null;
      }
      obj = new window.sirius.Data_sources();
      data_source = xml.children('data_source');
      obj.set('data_source', _.map($(data_source), function(data_source_i) {
        return $a.Data_source.from_xml2($(data_source_i), deferred, object_with_id);
      }));
      if (obj.resolve_references) {
        obj.resolve_references(deferred, object_with_id);
      }
      return obj;
    };

    Data_sources.prototype.to_xml = function(doc) {
      var xml;
      xml = doc.createElement('data_sources');
      if (this.encode_references) {
        this.encode_references();
      }
      _.each(this.get('data_source') || [], function(a_data_source) {
        return xml.appendChild(a_data_source.to_xml(doc));
      });
      return xml;
    };

    Data_sources.prototype.deep_copy = function() {
      return Data_sources.from_xml1(this.to_xml(), {});
    };

    Data_sources.prototype.inspect = function(depth, indent, orig_depth) {
      if (depth == null) {
        depth = 1;
      }
      if (indent == null) {
        indent = false;
      }
      if (orig_depth == null) {
        orig_depth = -1;
      }
      return null;
    };

    Data_sources.prototype.make_tree = function() {
      return null;
    };

    return Data_sources;

  })(Backbone.Model);

}).call(this);
