// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.sirius.Decision_point = (function(_super) {
    var $a;

    __extends(Decision_point, _super);

    /* $a = alias for sirius namespace
    */


    function Decision_point() {
      return Decision_point.__super__.constructor.apply(this, arguments);
    }

    $a = window.sirius;

    Decision_point.from_xml1 = function(xml, object_with_id) {
      var deferred, fn, obj, _i, _len;
      deferred = [];
      obj = this.from_xml2(xml, deferred, object_with_id);
      for (_i = 0, _len = deferred.length; _i < _len; _i++) {
        fn = deferred[_i];
        fn();
      }
      return obj;
    };

    Decision_point.from_xml2 = function(xml, deferred, object_with_id) {
      var VehicleTypeOrder, decision_point_split, dt, id, node_id, obj, start_time;
      if (!(xml != null) || xml.length === 0) {
        return null;
      }
      obj = new window.sirius.Decision_point();
      VehicleTypeOrder = xml.children('VehicleTypeOrder');
      obj.set('vehicletypeorder', $a.VehicleTypeOrder.from_xml2(VehicleTypeOrder, deferred, object_with_id));
      decision_point_split = xml.children('decision_point_split');
      obj.set('decision_point_split', _.map($(decision_point_split), function(decision_point_split_i) {
        return $a.Decision_point_split.from_xml2($(decision_point_split_i), deferred, object_with_id);
      }));
      id = $(xml).attr('id');
      obj.set('id', id);
      node_id = $(xml).attr('node_id');
      obj.set('node_id', node_id);
      start_time = $(xml).attr('start_time');
      obj.set('start_time', Number(start_time));
      dt = $(xml).attr('dt');
      obj.set('dt', Number(dt));
      if (obj.resolve_references) {
        obj.resolve_references(deferred, object_with_id);
      }
      return obj;
    };

    Decision_point.prototype.to_xml = function(doc) {
      var xml;
      xml = doc.createElement('decision_point');
      if (this.encode_references) {
        this.encode_references();
      }
      if (this.has('vehicletypeorder')) {
        xml.appendChild(this.get('vehicletypeorder').to_xml(doc));
      }
      _.each(this.get('decision_point_split') || [], function(a_decision_point_split) {
        return xml.appendChild(a_decision_point_split.to_xml(doc));
      });
      if (this.has('id')) {
        xml.setAttribute('id', this.get('id'));
      }
      if (this.has('node_id')) {
        xml.setAttribute('node_id', this.get('node_id'));
      }
      if (this.has('start_time') && this.start_time !== 0) {
        xml.setAttribute('start_time', this.get('start_time'));
      }
      if (this.has('dt')) {
        xml.setAttribute('dt', this.get('dt'));
      }
      return xml;
    };

    Decision_point.prototype.deep_copy = function() {
      return Decision_point.from_xml1(this.to_xml(), {});
    };

    Decision_point.prototype.inspect = function(depth, indent, orig_depth) {
      if (depth == null) {
        depth = 1;
      }
      if (indent == null) {
        indent = false;
      }
      if (orig_depth == null) {
        orig_depth = -1;
      }
      return null;
    };

    Decision_point.prototype.make_tree = function() {
      return null;
    };

    return Decision_point;

  })(Backbone.Model);

}).call(this);
