// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.sirius.DecisionPoints = (function(_super) {
    var $a;

    __extends(DecisionPoints, _super);

    /* $a = alias for sirius namespace
    */


    function DecisionPoints() {
      return DecisionPoints.__super__.constructor.apply(this, arguments);
    }

    $a = window.sirius;

    DecisionPoints.from_xml1 = function(xml, object_with_id) {
      var deferred, fn, obj, _i, _len;
      deferred = [];
      obj = this.from_xml2(xml, deferred, object_with_id);
      for (_i = 0, _len = deferred.length; _i < _len; _i++) {
        fn = deferred[_i];
        fn();
      }
      return obj;
    };

    DecisionPoints.from_xml2 = function(xml, deferred, object_with_id) {
      var decision_point, obj;
      if (!(xml != null) || xml.length === 0) {
        return null;
      }
      obj = new window.sirius.DecisionPoints();
      decision_point = xml.children('decision_point');
      obj.set('decision_point', _.map($(decision_point), function(decision_point_i) {
        return $a.Decision_point.from_xml2($(decision_point_i), deferred, object_with_id);
      }));
      if (obj.resolve_references) {
        obj.resolve_references(deferred, object_with_id);
      }
      return obj;
    };

    DecisionPoints.prototype.to_xml = function(doc) {
      var xml;
      xml = doc.createElement('DecisionPoints');
      if (this.encode_references) {
        this.encode_references();
      }
      _.each(this.get('decision_point') || [], function(a_decision_point) {
        return xml.appendChild(a_decision_point.to_xml(doc));
      });
      return xml;
    };

    DecisionPoints.prototype.deep_copy = function() {
      return DecisionPoints.from_xml1(this.to_xml(), {});
    };

    DecisionPoints.prototype.inspect = function(depth, indent, orig_depth) {
      if (depth == null) {
        depth = 1;
      }
      if (indent == null) {
        indent = false;
      }
      if (orig_depth == null) {
        orig_depth = -1;
      }
      return null;
    };

    DecisionPoints.prototype.make_tree = function() {
      return null;
    };

    return DecisionPoints;

  })(Backbone.Model);

}).call(this);
