// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.sirius.DemandProfile = (function(_super) {
    var $a;

    __extends(DemandProfile, _super);

    /* $a = alias for sirius namespace
    */


    function DemandProfile() {
      return DemandProfile.__super__.constructor.apply(this, arguments);
    }

    $a = window.sirius;

    DemandProfile.from_xml1 = function(xml, object_with_id) {
      var deferred, fn, obj, _i, _len;
      deferred = [];
      obj = this.from_xml2(xml, deferred, object_with_id);
      for (_i = 0, _len = deferred.length; _i < _len; _i++) {
        fn = deferred[_i];
        fn();
      }
      return obj;
    };

    DemandProfile.from_xml2 = function(xml, deferred, object_with_id) {
      var dt, knob, link_id_origin, obj, start_time, std_dev_add, std_dev_mult;
      if (!(xml != null) || xml.length === 0) {
        return null;
      }
      obj = new window.sirius.DemandProfile();
      knob = $(xml).attr('knob');
      obj.set('knob', Number(knob));
      start_time = $(xml).attr('start_time');
      obj.set('start_time', Number(start_time));
      dt = $(xml).attr('dt');
      obj.set('dt', Number(dt));
      link_id_origin = $(xml).attr('link_id_origin');
      obj.set('link_id_origin', link_id_origin);
      std_dev_add = $(xml).attr('std_dev_add');
      obj.set('std_dev_add', Number(std_dev_add));
      std_dev_mult = $(xml).attr('std_dev_mult');
      obj.set('std_dev_mult', Number(std_dev_mult));
      obj.set('text', xml.text());
      if (obj.resolve_references) {
        obj.resolve_references(deferred, object_with_id);
      }
      return obj;
    };

    DemandProfile.prototype.to_xml = function(doc) {
      var xml;
      xml = doc.createElement('demandProfile');
      if (this.encode_references) {
        this.encode_references();
      }
      if (this.has('knob')) {
        xml.setAttribute('knob', this.get('knob'));
      }
      if (this.has('start_time') && this.start_time !== 0) {
        xml.setAttribute('start_time', this.get('start_time'));
      }
      if (this.has('dt')) {
        xml.setAttribute('dt', this.get('dt'));
      }
      if (this.has('link_id_origin')) {
        xml.setAttribute('link_id_origin', this.get('link_id_origin'));
      }
      if (this.has('std_dev_add')) {
        xml.setAttribute('std_dev_add', this.get('std_dev_add'));
      }
      if (this.has('std_dev_mult')) {
        xml.setAttribute('std_dev_mult', this.get('std_dev_mult'));
      }
      xml.appendChild(doc.createTextNode($a.ArrayText.emit(this.get('text') || [])));
      return xml;
    };

    DemandProfile.prototype.deep_copy = function() {
      return DemandProfile.from_xml1(this.to_xml(), {});
    };

    DemandProfile.prototype.inspect = function(depth, indent, orig_depth) {
      if (depth == null) {
        depth = 1;
      }
      if (indent == null) {
        indent = false;
      }
      if (orig_depth == null) {
        orig_depth = -1;
      }
      return null;
    };

    DemandProfile.prototype.make_tree = function() {
      return null;
    };

    return DemandProfile;

  })(Backbone.Model);

}).call(this);
