// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.sirius.DirectionsCacheEntry = (function(_super) {
    var $a;

    __extends(DirectionsCacheEntry, _super);

    /* $a = alias for sirius namespace
    */


    function DirectionsCacheEntry() {
      return DirectionsCacheEntry.__super__.constructor.apply(this, arguments);
    }

    $a = window.sirius;

    DirectionsCacheEntry.from_xml1 = function(xml, object_with_id) {
      var deferred, fn, obj, _i, _len;
      deferred = [];
      obj = this.from_xml2(xml, deferred, object_with_id);
      for (_i = 0, _len = deferred.length; _i < _len; _i++) {
        fn = deferred[_i];
        fn();
      }
      return obj;
    };

    DirectionsCacheEntry.from_xml2 = function(xml, deferred, object_with_id) {
      var EncodedPolyline, From, To, avoidHighways, obj, road_name;
      if (!(xml != null) || xml.length === 0) {
        return null;
      }
      obj = new window.sirius.DirectionsCacheEntry();
      From = xml.children('From');
      obj.set('from', $a.From.from_xml2(From, deferred, object_with_id));
      To = xml.children('To');
      obj.set('to', $a.To.from_xml2(To, deferred, object_with_id));
      EncodedPolyline = xml.children('EncodedPolyline');
      obj.set('encodedpolyline', $a.EncodedPolyline.from_xml2(EncodedPolyline, deferred, object_with_id));
      avoidHighways = $(xml).attr('avoidHighways');
      obj.set('avoidHighways', avoidHighways != null ? avoidHighways.toString().toLowerCase() === 'true' : void 0);
      road_name = $(xml).attr('road_name');
      obj.set('road_name', road_name);
      if (obj.resolve_references) {
        obj.resolve_references(deferred, object_with_id);
      }
      return obj;
    };

    DirectionsCacheEntry.prototype.to_xml = function(doc) {
      var xml;
      xml = doc.createElement('DirectionsCacheEntry');
      if (this.encode_references) {
        this.encode_references();
      }
      if (this.has('from')) {
        xml.appendChild(this.get('from').to_xml(doc));
      }
      if (this.has('to')) {
        xml.appendChild(this.get('to').to_xml(doc));
      }
      if (this.has('encodedpolyline')) {
        xml.appendChild(this.get('encodedpolyline').to_xml(doc));
      }
      if (this.has('avoidHighways')) {
        xml.setAttribute('avoidHighways', this.get('avoidHighways'));
      }
      if (this.has('road_name')) {
        xml.setAttribute('road_name', this.get('road_name'));
      }
      return xml;
    };

    DirectionsCacheEntry.prototype.deep_copy = function() {
      return DirectionsCacheEntry.from_xml1(this.to_xml(), {});
    };

    DirectionsCacheEntry.prototype.inspect = function(depth, indent, orig_depth) {
      if (depth == null) {
        depth = 1;
      }
      if (indent == null) {
        indent = false;
      }
      if (orig_depth == null) {
        orig_depth = -1;
      }
      return null;
    };

    DirectionsCacheEntry.prototype.make_tree = function() {
      return null;
    };

    return DirectionsCacheEntry;

  })(Backbone.Model);

}).call(this);
