// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.sirius.EncodedPolyline = (function(_super) {
    var $a;

    __extends(EncodedPolyline, _super);

    /* $a = alias for sirius namespace
    */


    function EncodedPolyline() {
      return EncodedPolyline.__super__.constructor.apply(this, arguments);
    }

    $a = window.sirius;

    EncodedPolyline.from_xml1 = function(xml, object_with_id) {
      var deferred, fn, obj, _i, _len;
      deferred = [];
      obj = this.from_xml2(xml, deferred, object_with_id);
      for (_i = 0, _len = deferred.length; _i < _len; _i++) {
        fn = deferred[_i];
        fn();
      }
      return obj;
    };

    EncodedPolyline.from_xml2 = function(xml, deferred, object_with_id) {
      var Levels, Points, numLevels, obj, zoomFactor;
      if (!(xml != null) || xml.length === 0) {
        return null;
      }
      obj = new window.sirius.EncodedPolyline();
      Points = xml.children('Points');
      obj.set('points', $a.Points.from_xml2(Points, deferred, object_with_id));
      Levels = xml.children('Levels');
      obj.set('levels', $a.Levels.from_xml2(Levels, deferred, object_with_id));
      zoomFactor = $(xml).attr('zoomFactor');
      obj.set('zoomFactor', Number(zoomFactor));
      numLevels = $(xml).attr('numLevels');
      obj.set('numLevels', Number(numLevels));
      if (obj.resolve_references) {
        obj.resolve_references(deferred, object_with_id);
      }
      return obj;
    };

    EncodedPolyline.prototype.to_xml = function(doc) {
      var xml;
      xml = doc.createElement('EncodedPolyline');
      if (this.encode_references) {
        this.encode_references();
      }
      if (this.has('points')) {
        xml.appendChild(this.get('points').to_xml(doc));
      }
      if (this.has('levels')) {
        xml.appendChild(this.get('levels').to_xml(doc));
      }
      if (this.has('zoomFactor')) {
        xml.setAttribute('zoomFactor', this.get('zoomFactor'));
      }
      if (this.has('numLevels')) {
        xml.setAttribute('numLevels', this.get('numLevels'));
      }
      return xml;
    };

    EncodedPolyline.prototype.deep_copy = function() {
      return EncodedPolyline.from_xml1(this.to_xml(), {});
    };

    EncodedPolyline.prototype.inspect = function(depth, indent, orig_depth) {
      if (depth == null) {
        depth = 1;
      }
      if (indent == null) {
        indent = false;
      }
      if (orig_depth == null) {
        orig_depth = -1;
      }
      return null;
    };

    EncodedPolyline.prototype.make_tree = function() {
      return null;
    };

    return EncodedPolyline;

  })(Backbone.Model);

}).call(this);
