// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.sirius.Input = (function(_super) {
    var $a;

    __extends(Input, _super);

    /* $a = alias for sirius namespace
    */


    function Input() {
      return Input.__super__.constructor.apply(this, arguments);
    }

    $a = window.sirius;

    Input.from_xml1 = function(xml, object_with_id) {
      var deferred, fn, obj, _i, _len;
      deferred = [];
      obj = this.from_xml2(xml, deferred, object_with_id);
      for (_i = 0, _len = deferred.length; _i < _len; _i++) {
        fn = deferred[_i];
        fn();
      }
      return obj;
    };

    Input.from_xml2 = function(xml, deferred, object_with_id) {
      var link_id, obj;
      if (!(xml != null) || xml.length === 0) {
        return null;
      }
      obj = new window.sirius.Input();
      link_id = $(xml).attr('link_id');
      obj.set('link_id', link_id);
      if (obj.resolve_references) {
        obj.resolve_references(deferred, object_with_id);
      }
      return obj;
    };

    Input.prototype.to_xml = function(doc) {
      var xml;
      xml = doc.createElement('input');
      if (this.encode_references) {
        this.encode_references();
      }
      if (this.has('link_id')) {
        xml.setAttribute('link_id', this.get('link_id'));
      }
      return xml;
    };

    Input.prototype.deep_copy = function() {
      return Input.from_xml1(this.to_xml(), {});
    };

    Input.prototype.inspect = function(depth, indent, orig_depth) {
      if (depth == null) {
        depth = 1;
      }
      if (indent == null) {
        indent = false;
      }
      if (orig_depth == null) {
        orig_depth = -1;
      }
      return null;
    };

    Input.prototype.make_tree = function() {
      return null;
    };

    return Input;

  })(Backbone.Model);

}).call(this);
