// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.sirius.IntersectionCacheEntry = (function(_super) {
    var $a;

    __extends(IntersectionCacheEntry, _super);

    /* $a = alias for sirius namespace
    */


    function IntersectionCacheEntry() {
      return IntersectionCacheEntry.__super__.constructor.apply(this, arguments);
    }

    $a = window.sirius;

    IntersectionCacheEntry.from_xml1 = function(xml, object_with_id) {
      var deferred, fn, obj, _i, _len;
      deferred = [];
      obj = this.from_xml2(xml, deferred, object_with_id);
      for (_i = 0, _len = deferred.length; _i < _len; _i++) {
        fn = deferred[_i];
        fn();
      }
      return obj;
    };

    IntersectionCacheEntry.from_xml2 = function(xml, deferred, object_with_id) {
      var lat, lng, obj, qlat, qlng, street1, street2;
      if (!(xml != null) || xml.length === 0) {
        return null;
      }
      obj = new window.sirius.IntersectionCacheEntry();
      qlat = $(xml).attr('qlat');
      obj.set('qlat', Number(qlat));
      qlng = $(xml).attr('qlng');
      obj.set('qlng', Number(qlng));
      lat = $(xml).attr('lat');
      obj.set('lat', Number(lat));
      lng = $(xml).attr('lng');
      obj.set('lng', Number(lng));
      street1 = $(xml).attr('street1');
      obj.set('street1', street1);
      street2 = $(xml).attr('street2');
      obj.set('street2', street2);
      if (obj.resolve_references) {
        obj.resolve_references(deferred, object_with_id);
      }
      return obj;
    };

    IntersectionCacheEntry.prototype.to_xml = function(doc) {
      var xml;
      xml = doc.createElement('IntersectionCacheEntry');
      if (this.encode_references) {
        this.encode_references();
      }
      if (this.has('qlat')) {
        xml.setAttribute('qlat', this.get('qlat'));
      }
      if (this.has('qlng')) {
        xml.setAttribute('qlng', this.get('qlng'));
      }
      if (this.has('lat')) {
        xml.setAttribute('lat', this.get('lat'));
      }
      if (this.has('lng')) {
        xml.setAttribute('lng', this.get('lng'));
      }
      if (this.has('street1')) {
        xml.setAttribute('street1', this.get('street1'));
      }
      if (this.has('street2')) {
        xml.setAttribute('street2', this.get('street2'));
      }
      return xml;
    };

    IntersectionCacheEntry.prototype.deep_copy = function() {
      return IntersectionCacheEntry.from_xml1(this.to_xml(), {});
    };

    IntersectionCacheEntry.prototype.inspect = function(depth, indent, orig_depth) {
      if (depth == null) {
        depth = 1;
      }
      if (indent == null) {
        indent = false;
      }
      if (orig_depth == null) {
        orig_depth = -1;
      }
      return null;
    };

    IntersectionCacheEntry.prototype.make_tree = function() {
      return null;
    };

    return IntersectionCacheEntry;

  })(Backbone.Model);

}).call(this);
