// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.sirius.Intersection = (function(_super) {
    var $a;

    __extends(Intersection, _super);

    /* $a = alias for sirius namespace
    */


    function Intersection() {
      return Intersection.__super__.constructor.apply(this, arguments);
    }

    $a = window.sirius;

    Intersection.from_xml1 = function(xml, object_with_id) {
      var deferred, fn, obj, _i, _len;
      deferred = [];
      obj = this.from_xml2(xml, deferred, object_with_id);
      for (_i = 0, _len = deferred.length; _i < _len; _i++) {
        fn = deferred[_i];
        fn();
      }
      return obj;
    };

    Intersection.from_xml2 = function(xml, deferred, object_with_id) {
      var node_id, obj, offset, stage;
      if (!(xml != null) || xml.length === 0) {
        return null;
      }
      obj = new window.sirius.Intersection();
      stage = xml.children('stage');
      obj.set('stage', _.map($(stage), function(stage_i) {
        return $a.Stage.from_xml2($(stage_i), deferred, object_with_id);
      }));
      node_id = $(xml).attr('node_id');
      obj.set('node_id', node_id);
      offset = $(xml).attr('offset');
      obj.set('offset', Number(offset));
      if (obj.resolve_references) {
        obj.resolve_references(deferred, object_with_id);
      }
      return obj;
    };

    Intersection.prototype.to_xml = function(doc) {
      var xml;
      xml = doc.createElement('intersection');
      if (this.encode_references) {
        this.encode_references();
      }
      _.each(this.get('stage') || [], function(a_stage) {
        return xml.appendChild(a_stage.to_xml(doc));
      });
      if (this.has('node_id')) {
        xml.setAttribute('node_id', this.get('node_id'));
      }
      if (this.has('offset')) {
        xml.setAttribute('offset', this.get('offset'));
      }
      return xml;
    };

    Intersection.prototype.deep_copy = function() {
      return Intersection.from_xml1(this.to_xml(), {});
    };

    Intersection.prototype.inspect = function(depth, indent, orig_depth) {
      if (depth == null) {
        depth = 1;
      }
      if (indent == null) {
        indent = false;
      }
      if (orig_depth == null) {
        orig_depth = -1;
      }
      return null;
    };

    Intersection.prototype.make_tree = function() {
      return null;
    };

    return Intersection;

  })(Backbone.Model);

}).call(this);
