// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.sirius.Lane_count_change = (function(_super) {
    var $a;

    __extends(Lane_count_change, _super);

    /* $a = alias for sirius namespace
    */


    function Lane_count_change() {
      return Lane_count_change.__super__.constructor.apply(this, arguments);
    }

    $a = window.sirius;

    Lane_count_change.from_xml1 = function(xml, object_with_id) {
      var deferred, fn, obj, _i, _len;
      deferred = [];
      obj = this.from_xml2(xml, deferred, object_with_id);
      for (_i = 0, _len = deferred.length; _i < _len; _i++) {
        fn = deferred[_i];
        fn();
      }
      return obj;
    };

    Lane_count_change.from_xml2 = function(xml, deferred, object_with_id) {
      var delta, obj;
      if (!(xml != null) || xml.length === 0) {
        return null;
      }
      obj = new window.sirius.Lane_count_change();
      delta = $(xml).attr('delta');
      obj.set('delta', Number(delta));
      if (obj.resolve_references) {
        obj.resolve_references(deferred, object_with_id);
      }
      return obj;
    };

    Lane_count_change.prototype.to_xml = function(doc) {
      var xml;
      xml = doc.createElement('lane_count_change');
      if (this.encode_references) {
        this.encode_references();
      }
      if (this.has('delta') && this.delta !== 0) {
        xml.setAttribute('delta', this.get('delta'));
      }
      return xml;
    };

    Lane_count_change.prototype.deep_copy = function() {
      return Lane_count_change.from_xml1(this.to_xml(), {});
    };

    Lane_count_change.prototype.inspect = function(depth, indent, orig_depth) {
      if (depth == null) {
        depth = 1;
      }
      if (indent == null) {
        indent = false;
      }
      if (orig_depth == null) {
        orig_depth = -1;
      }
      return null;
    };

    Lane_count_change.prototype.make_tree = function() {
      return null;
    };

    return Lane_count_change;

  })(Backbone.Model);

}).call(this);
