// Generated by CoffeeScript 1.3.3
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.sirius.LayersMenuView = (function(_super) {
    var $a;

    __extends(LayersMenuView, _super);

    function LayersMenuView() {
      this.hoverSubOff = __bind(this.hoverSubOff, this);
      return LayersMenuView.__super__.constructor.apply(this, arguments);
    }

    $a = window.sirius;

    LayersMenuView.prototype.tagName = 'ul';

    LayersMenuView.prototype.events = {
      "mouseenter .submenu": "hoverSubOn",
      "mouseleave .submenu": "hoverSubOff",
      "mouseleave": "displayOff",
      "mouseenter": "displayOn"
    };

    LayersMenuView.prototype.initialize = function(options) {
      var _this = this;
      this.options = options;
      this.menuItems = this.options.menuItems;
      if (this.options.className) {
        this.$el.attr('class', this.options.className);
      }
      if (this.options.id) {
        this.$el.attr('id', this.options.id);
      }
      this.render();
      return _.each(this.menuItems, function(item) {
        return new $a.LayersMenuViewItem(_this.id, item);
      });
    };

    LayersMenuView.prototype.render = function() {
      $("#" + this.options.parentId).append(this.el);
      return this;
    };

    LayersMenuView.prototype.displayOff = function(e) {
      return this.$el.removeClass("open");
    };

    LayersMenuView.prototype.displayOn = function(e) {
      return this.$el.addClass("open");
    };

    LayersMenuView.prototype.hoverSubOn = function(e) {
      var ul;
      ul = $("#" + e.currentTarget.id).children("ul");
      return ul.removeClass("submenu-hide").addClass("submenu-show");
    };

    LayersMenuView.prototype.hoverSubOff = function(e) {
      var ul;
      ul = $("#" + e.currentTarget.id).children("ul");
      return ul.removeClass("submenu-show").addClass("submenu-hide");
    };

    return LayersMenuView;

  })(Backbone.View);

}).call(this);
