// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.sirius.Levels = (function(_super) {
    var $a;

    __extends(Levels, _super);

    /* $a = alias for sirius namespace
    */


    function Levels() {
      return Levels.__super__.constructor.apply(this, arguments);
    }

    $a = window.sirius;

    Levels.from_xml1 = function(xml, object_with_id) {
      var deferred, fn, obj, _i, _len;
      deferred = [];
      obj = this.from_xml2(xml, deferred, object_with_id);
      for (_i = 0, _len = deferred.length; _i < _len; _i++) {
        fn = deferred[_i];
        fn();
      }
      return obj;
    };

    Levels.from_xml2 = function(xml, deferred, object_with_id) {
      var obj;
      if (!(xml != null) || xml.length === 0) {
        return null;
      }
      obj = new window.sirius.Levels();
      obj.set('text', xml.text());
      if (obj.resolve_references) {
        obj.resolve_references(deferred, object_with_id);
      }
      return obj;
    };

    Levels.prototype.to_xml = function(doc) {
      var xml;
      xml = doc.createElement('Levels');
      if (this.encode_references) {
        this.encode_references();
      }
      xml.appendChild(doc.createTextNode($a.ArrayText.emit(this.get('text') || [])));
      return xml;
    };

    Levels.prototype.deep_copy = function() {
      return Levels.from_xml1(this.to_xml(), {});
    };

    Levels.prototype.inspect = function(depth, indent, orig_depth) {
      if (depth == null) {
        depth = 1;
      }
      if (indent == null) {
        indent = false;
      }
      if (orig_depth == null) {
        orig_depth = -1;
      }
      return null;
    };

    Levels.prototype.make_tree = function() {
      return null;
    };

    return Levels;

  })(Backbone.Model);

}).call(this);
