// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.sirius.Links = (function(_super) {
    var $a;

    __extends(Links, _super);

    /* $a = alias for sirius namespace
    */


    function Links() {
      return Links.__super__.constructor.apply(this, arguments);
    }

    $a = window.sirius;

    Links.from_xml1 = function(xml, object_with_id) {
      var deferred, fn, obj, _i, _len;
      deferred = [];
      obj = this.from_xml2(xml, deferred, object_with_id);
      for (_i = 0, _len = deferred.length; _i < _len; _i++) {
        fn = deferred[_i];
        fn();
      }
      return obj;
    };

    Links.from_xml2 = function(xml, deferred, object_with_id) {
      var link_reference, obj;
      if (!(xml != null) || xml.length === 0) {
        return null;
      }
      obj = new window.sirius.Links();
      link_reference = xml.children('link_reference');
      obj.set('link_reference', _.map($(link_reference), function(link_reference_i) {
        return $a.Link_reference.from_xml2($(link_reference_i), deferred, object_with_id);
      }));
      if (obj.resolve_references) {
        obj.resolve_references(deferred, object_with_id);
      }
      return obj;
    };

    Links.prototype.to_xml = function(doc) {
      var xml;
      xml = doc.createElement('links');
      if (this.encode_references) {
        this.encode_references();
      }
      _.each(this.get('link_reference') || [], function(a_link_reference) {
        return xml.appendChild(a_link_reference.to_xml(doc));
      });
      return xml;
    };

    Links.prototype.deep_copy = function() {
      return Links.from_xml1(this.to_xml(), {});
    };

    Links.prototype.inspect = function(depth, indent, orig_depth) {
      if (depth == null) {
        depth = 1;
      }
      if (indent == null) {
        indent = false;
      }
      if (orig_depth == null) {
        orig_depth = -1;
      }
      return null;
    };

    Links.prototype.make_tree = function() {
      return null;
    };

    return Links;

  })(Backbone.Model);

}).call(this);
