// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.sirius.LinkCollection = (function(_super) {
    var $a;

    __extends(LinkCollection, _super);

    function LinkCollection() {
      return LinkCollection.__super__.constructor.apply(this, arguments);
    }

    $a = window.sirius;

    LinkCollection.prototype.model = $a.Link;

    LinkCollection.prototype.getBrowserColumnData = function() {
      return this.models.map(function(link) {
        return [link.get('id'), link.get('name'), link.get('road_name'), link.get('type'), link.get('lanes'), link.get('begin').get('node').get('name'), link.get('end').get('node').get('name')];
      });
    };

    return LinkCollection;

  })(Backbone.Collection);

}).call(this);
