// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.sirius.Linkpair = (function(_super) {
    var $a;

    __extends(Linkpair, _super);

    /* $a = alias for sirius namespace
    */


    function Linkpair() {
      return Linkpair.__super__.constructor.apply(this, arguments);
    }

    $a = window.sirius;

    Linkpair.from_xml1 = function(xml, object_with_id) {
      var deferred, fn, obj, _i, _len;
      deferred = [];
      obj = this.from_xml2(xml, deferred, object_with_id);
      for (_i = 0, _len = deferred.length; _i < _len; _i++) {
        fn = deferred[_i];
        fn();
      }
      return obj;
    };

    Linkpair.from_xml2 = function(xml, deferred, object_with_id) {
      var link_a, link_b, obj;
      if (!(xml != null) || xml.length === 0) {
        return null;
      }
      obj = new window.sirius.Linkpair();
      link_a = $(xml).attr('link_a');
      obj.set('link_a', link_a);
      link_b = $(xml).attr('link_b');
      obj.set('link_b', link_b);
      if (obj.resolve_references) {
        obj.resolve_references(deferred, object_with_id);
      }
      return obj;
    };

    Linkpair.prototype.to_xml = function(doc) {
      var xml;
      xml = doc.createElement('linkpair');
      if (this.encode_references) {
        this.encode_references();
      }
      if (this.has('link_a')) {
        xml.setAttribute('link_a', this.get('link_a'));
      }
      if (this.has('link_b')) {
        xml.setAttribute('link_b', this.get('link_b'));
      }
      return xml;
    };

    Linkpair.prototype.deep_copy = function() {
      return Linkpair.from_xml1(this.to_xml(), {});
    };

    Linkpair.prototype.inspect = function(depth, indent, orig_depth) {
      if (depth == null) {
        depth = 1;
      }
      if (indent == null) {
        indent = false;
      }
      if (orig_depth == null) {
        orig_depth = -1;
      }
      return null;
    };

    Linkpair.prototype.make_tree = function() {
      return null;
    };

    return Linkpair;

  })(Backbone.Model);

}).call(this);
