// Generated by CoffeeScript 1.3.3
(function() {
  var load_sirius_classes;

  load_sirius_classes = function(after) {
    return head.js("js/Sirius.js", function() {
      var class_paths;
      class_paths = _.map(window.sirius.sirius_classes_without_extensions, function(cname) {
        return "js/" + cname + ".js";
      });
      class_paths = class_paths.concat(_.flatten(_.map(window.sirius.sirius_map_view_classes, function(cname) {
        return "js/" + cname + ".js";
      })));
      class_paths = class_paths.concat(_.flatten(_.map(window.sirius.sirius_classes_with_extensions, function(cname) {
        return ["js/" + cname + ".js", "js/extensions/" + cname + ".js"];
      })));
      class_paths = class_paths.concat(_.flatten(_.map(window.sirius.sirius_collection_classes, function(cname) {
        return "js/" + cname + ".js";
      })));
      class_paths.push(after);
      return head.js.apply(this, class_paths);
    });
  };

  window.load_sirius = function() {
    return head.js("js/Sirius.js", 'js/menu-data.js', 'js/sirius-classes-load.js', function() {
      return load_sirius_classes(function() {
        return new window.sirius.AppView();
      });
    });
  };

  head.js('https://www.google.com/jsapi', '../lib/js/jquery-1.7.1.js', '../lib/js/jquery-ui-1.8.21/js/jquery-ui-1.8.21.min.js', '../lib/js/underscore.js', '../lib/js/backbone.js', '../lib/js/jquery.dataTables.min.js', '../lib/js/jquery.layout.min-1.2.0.js', '../lib/js/d3.v2.js', '../lib/js/bootstrap/js/bootstrap.min.js', function() {
    return google.load("maps", "3", {
      callback: "window.load_sirius()",
      other_params: "libraries=geometry,drawing&sensor=false"
    });
  });

}).call(this);
