// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.sirius.MapControllerView = (function(_super) {
    var $a;

    __extends(MapControllerView, _super);

    function MapControllerView() {
      return MapControllerView.__super__.constructor.apply(this, arguments);
    }

    MapControllerView.ICON = 'controller-deselected';

    MapControllerView.SELECTED_ICON = 'controller-selected';

    $a = window.sirius;

    MapControllerView.prototype.initialize = function(model) {
      MapControllerView.__super__.initialize.call(this, model);
      $a.broker.on('map:hide_controller_layer', this.hideMarker, this);
      return $a.broker.on('map:show_controller_layer', this.showMarker, this);
    };

    MapControllerView.prototype.getIcon = function() {
      return MapControllerView.__super__.getIcon.call(this, MapControllerView.ICON);
    };

    MapControllerView.prototype.removeElement = function() {
      $a.broker.off('map:hide_controller_layer');
      $a.broker.off('map:show_controller_layer');
      return MapControllerView.__super__.removeElement.apply(this, arguments);
    };

    MapControllerView.prototype.manageMarkerSelect = function() {
      var iconName;
      iconName = MapControllerView.__super__._getIconName.apply(this, []);
      if (iconName === ("" + MapControllerView.ICON + ".png")) {
        this._triggerClearSelectEvents();
        $a.broker.trigger("app:tree_highlight:" + this.model.cid);
        return this.makeSelected();
      } else {
        this._triggerClearSelectEvents();
        return this.clearSelected();
      }
    };

    MapControllerView.prototype._triggerClearSelectEvents = function() {
      if (!$a.SHIFT_DOWN) {
        $a.broker.trigger('map:clear_selected');
      }
      if (!$a.SHIFT_DOWN) {
        return $a.broker.trigger('app:tree_remove_highlight');
      }
    };

    MapControllerView.prototype.makeSelected = function() {
      _.each(this.model.get('targetreferences'), function(link) {
        $a.broker.trigger("map:select_item:" + link.cid);
        return $a.broker.trigger("app:tree_highlight:" + link.cid);
      });
      return MapControllerView.__super__.makeSelected.call(this, MapControllerView.SELECTED_ICON);
    };

    MapControllerView.prototype.clearSelected = function() {
      return MapControllerView.__super__.clearSelected.call(this, MapControllerView.ICON);
    };

    return MapControllerView;

  })(window.sirius.MapMarkerView);

}).call(this);
