// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.sirius.MapSensorView = (function(_super) {
    var $a;

    __extends(MapSensorView, _super);

    function MapSensorView() {
      return MapSensorView.__super__.constructor.apply(this, arguments);
    }

    MapSensorView.ICON = 'camera-orig';

    MapSensorView.SELECTED_ICON = 'camera-selected';

    $a = window.sirius;

    MapSensorView.prototype.initialize = function(model) {
      MapSensorView.__super__.initialize.call(this, model);
      this._contextMenu();
      $a.broker.on("map:select_neighbors:" + this.model.cid, this.selectSelfandMyLinks, this);
      $a.broker.on("map:clear_neighbors:" + this.model.cid, this.clearSelfandMyLinks, this);
      $a.broker.on('map:hide_sensor_layer', this.hideMarker, this);
      return $a.broker.on('map:show_sensor_layer', this.showMarker, this);
    };

    MapSensorView.prototype.getIcon = function() {
      return MapSensorView.__super__.getIcon.call(this, MapSensorView.ICON);
    };

    MapSensorView.prototype._editor = function() {
      var env;
      env = new $a.EditorSensorView({
        elem: 'sensor',
        models: [this.model],
        width: 300
      });
      $('body').append(env.el);
      env.render();
      $(env.el).tabs();
      return $(env.el).dialog('open');
    };

    MapSensorView.prototype.removeElement = function() {
      $a.broker.off("map:select_neighbors:" + this.model.cid);
      $a.broker.off("map:clear_neighbors:" + this.model.cid);
      $a.broker.off('map:hide_sensor_layer');
      $a.broker.off('map:show_sensor_layer');
      return MapSensorView.__super__.removeElement.apply(this, arguments);
    };

    MapSensorView.prototype._contextMenu = function() {
      return MapSensorView.__super__._contextMenu.call(this, 'sensor', $a.sensor_context_menu);
    };

    MapSensorView.prototype.manageMarkerSelect = function() {
      var iconName;
      iconName = MapSensorView.__super__._getIconName.apply(this, []);
      if (iconName === ("" + MapSensorView.ICON + ".png")) {
        this._triggerClearSelectEvents();
        $a.broker.trigger("app:tree_highlight:" + (this.model.get('link').cid));
        return this.makeSelected();
      } else {
        this._triggerClearSelectEvents();
        return this.clearSelected();
      }
    };

    MapSensorView.prototype._triggerClearSelectEvents = function() {
      if (!$a.SHIFT_DOWN) {
        $a.broker.trigger('map:clear_selected');
      }
      if (!$a.SHIFT_DOWN) {
        return $a.broker.trigger('app:tree_remove_highlight');
      }
    };

    MapSensorView.prototype.selectSelfandMyLinks = function() {
      this._triggerClearSelectEvents();
      this.makeSelected();
      $a.broker.trigger("app:tree_highlight:" + (this.model.get('link').cid));
      return $a.broker.trigger("map:select_item:" + (this.model.get('link').cid));
    };

    MapSensorView.prototype.clearSelfandMyLinks = function() {
      this.clearSelected();
      $a.broker.trigger("map:clear_item:" + (this.model.get('link').cid));
      return $a.broker.trigger("app:tree_remove_highlight:" + (this.model.get('link').cid));
    };

    MapSensorView.prototype.makeSelected = function() {
      return MapSensorView.__super__.makeSelected.call(this, MapSensorView.SELECTED_ICON);
    };

    MapSensorView.prototype.clearSelected = function() {
      return MapSensorView.__super__.clearSelected.call(this, MapSensorView.ICON);
    };

    return MapSensorView;

  })(window.sirius.MapMarkerView);

}).call(this);
