// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.sirius.MessagePanelView = (function(_super) {
    var $a;

    __extends(MessagePanelView, _super);

    function MessagePanelView() {
      return MessagePanelView.__super__.constructor.apply(this, arguments);
    }

    $a = window.sirius;

    MessagePanelView.prototype.className = 'alert alert-bottom close';

    MessagePanelView.prototype.initialize = function() {
      this.template = _.template($('#message-panel-template').html());
      $a.broker.on("app:show_message:success", this.success, this);
      $a.broker.on("app:show_message:error", this.error, this);
      $a.broker.on("app:show_message:info", this.info, this);
      return this.render();
    };

    MessagePanelView.prototype.render = function() {
      return $('body').append(this.el);
    };

    MessagePanelView.prototype.show = function(message, type) {
      var _this = this;
      this.$el.addClass("" + type);
      this.$el.html(this.template({
        message: message
      }));
      return this.$el.fadeIn(2000, function() {
        return _this.$el.fadeOut(2000);
      });
    };

    MessagePanelView.prototype.success = function(message) {
      return this.show(message, 'alert-success');
    };

    MessagePanelView.prototype.error = function(message) {
      return this.show(message, 'alert-error');
    };

    MessagePanelView.prototype.info = function(message) {
      return this.show(message, 'alert-info');
    };

    return MessagePanelView;

  })(Backbone.View);

}).call(this);
