// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.sirius.NavBarView = (function(_super) {
    var $a;

    __extends(NavBarView, _super);

    function NavBarView() {
      return NavBarView.__super__.constructor.apply(this, arguments);
    }

    $a = window.sirius;

    NavBarView.prototype.tagName = "ul";

    NavBarView.prototype.className = "nav";

    NavBarView.prototype.initialize = function(args) {
      var attrs, event, key, keyLower, subkey, values, _ref, _results;
      this.parent = args.attach;
      this.render();
      _ref = args.menuItems;
      _results = [];
      for (key in _ref) {
        values = _ref[key];
        keyLower = $a.Util.toLowerCaseAndDashed(key);
        attrs = {
          text: key,
          textLower: keyLower,
          attach: "." + this.className
        };
        new $a.NavParentItemView(attrs);
        _results.push((function() {
          var _results1;
          _results1 = [];
          for (subkey in values) {
            event = values[subkey];
            attrs = {
              text: subkey,
              textLower: $a.Util.toLowerCaseAndDashed(subkey),
              event: event,
              attach: keyLower
            };
            _results1.push(new $a.NavChildItemView(attrs));
          }
          return _results1;
        })());
      }
      return _results;
    };

    NavBarView.prototype.render = function() {
      $(this.parent).append(this.el);
      return this;
    };

    return NavBarView;

  })(Backbone.View);

}).call(this);
