// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.sirius.NavChildItemView = (function(_super) {
    var $a;

    __extends(NavChildItemView, _super);

    function NavChildItemView() {
      return NavChildItemView.__super__.constructor.apply(this, arguments);
    }

    $a = window.sirius;

    NavChildItemView.prototype.tagName = "li";

    NavChildItemView.prototype.initialize = function(args) {
      $(this.el).attr('id', args.textLower);
      this.parent = args.attach;
      this.template = _.template($("#child-item-menu-template").html());
      this.$el.html(this.template({
        text: args.text
      }));
      this.events = {
        'click': args.event
      };
      $a.broker.on('app:nav-menu', this.render, this);
      return this.render();
    };

    NavChildItemView.prototype.render = function() {
      $("#" + this.parent + " ul").append(this.el);
      return this;
    };

    return NavChildItemView;

  })(Backbone.View);

}).call(this);
