// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.sirius.NavParentItemView = (function(_super) {
    var $a;

    __extends(NavParentItemView, _super);

    function NavParentItemView() {
      return NavParentItemView.__super__.constructor.apply(this, arguments);
    }

    $a = window.sirius;

    NavParentItemView.prototype.tagName = "li";

    NavParentItemView.prototype.className = "dropdown active";

    NavParentItemView.prototype.initialize = function(args) {
      $(this.el).attr('id', args.textLower);
      this.parent = args.attach;
      this.template = _.template($("#parent-item-menu-template").html());
      this.$el.html(this.template(args));
      $a.broker.on('app:nav-menu', this.render, this);
      return this.render();
    };

    NavParentItemView.prototype.render = function() {
      $(this.parent).append(this.el);
      return this;
    };

    return NavParentItemView;

  })(Backbone.View);

}).call(this);
