// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.sirius.NetworkConnections = (function(_super) {
    var $a;

    __extends(NetworkConnections, _super);

    /* $a = alias for sirius namespace
    */


    function NetworkConnections() {
      return NetworkConnections.__super__.constructor.apply(this, arguments);
    }

    $a = window.sirius;

    NetworkConnections.from_xml1 = function(xml, object_with_id) {
      var deferred, fn, obj, _i, _len;
      deferred = [];
      obj = this.from_xml2(xml, deferred, object_with_id);
      for (_i = 0, _len = deferred.length; _i < _len; _i++) {
        fn = deferred[_i];
        fn();
      }
      return obj;
    };

    NetworkConnections.from_xml2 = function(xml, deferred, object_with_id) {
      var description, id, name, networkpair, obj;
      if (!(xml != null) || xml.length === 0) {
        return null;
      }
      obj = new window.sirius.NetworkConnections();
      description = xml.children('description');
      obj.set('description', $a.Description.from_xml2(description, deferred, object_with_id));
      networkpair = xml.children('networkpair');
      obj.set('networkpair', _.map($(networkpair), function(networkpair_i) {
        return $a.Networkpair.from_xml2($(networkpair_i), deferred, object_with_id);
      }));
      id = $(xml).attr('id');
      obj.set('id', id);
      name = $(xml).attr('name');
      obj.set('name', name);
      if (obj.resolve_references) {
        obj.resolve_references(deferred, object_with_id);
      }
      return obj;
    };

    NetworkConnections.prototype.to_xml = function(doc) {
      var xml;
      xml = doc.createElement('NetworkConnections');
      if (this.encode_references) {
        this.encode_references();
      }
      if (this.has('description')) {
        xml.appendChild(this.get('description').to_xml(doc));
      }
      _.each(this.get('networkpair') || [], function(a_networkpair) {
        return xml.appendChild(a_networkpair.to_xml(doc));
      });
      if (this.has('id') && this.id !== "") {
        xml.setAttribute('id', this.get('id'));
      }
      if (this.has('name') && this.name !== "") {
        xml.setAttribute('name', this.get('name'));
      }
      return xml;
    };

    NetworkConnections.prototype.deep_copy = function() {
      return NetworkConnections.from_xml1(this.to_xml(), {});
    };

    NetworkConnections.prototype.inspect = function(depth, indent, orig_depth) {
      if (depth == null) {
        depth = 1;
      }
      if (indent == null) {
        indent = false;
      }
      if (orig_depth == null) {
        orig_depth = -1;
      }
      return null;
    };

    NetworkConnections.prototype.make_tree = function() {
      return null;
    };

    return NetworkConnections;

  })(Backbone.Model);

}).call(this);
