// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.sirius.Network = (function(_super) {
    var $a;

    __extends(Network, _super);

    /* $a = alias for sirius namespace
    */


    function Network() {
      return Network.__super__.constructor.apply(this, arguments);
    }

    $a = window.sirius;

    Network.from_xml1 = function(xml, object_with_id) {
      var deferred, fn, obj, _i, _len;
      deferred = [];
      obj = this.from_xml2(xml, deferred, object_with_id);
      for (_i = 0, _len = deferred.length; _i < _len; _i++) {
        fn = deferred[_i];
        fn();
      }
      return obj;
    };

    Network.from_xml2 = function(xml, deferred, object_with_id) {
      var DirectionsCache, IntersectionCache, LinkList, NodeList, description, dt, id, name, obj, position;
      if (!(xml != null) || xml.length === 0) {
        return null;
      }
      obj = new window.sirius.Network();
      description = xml.children('description');
      obj.set('description', $a.Description.from_xml2(description, deferred, object_with_id));
      position = xml.children('position');
      obj.set('position', $a.Position.from_xml2(position, deferred, object_with_id));
      NodeList = xml.children('NodeList');
      obj.set('nodelist', $a.NodeList.from_xml2(NodeList, deferred, object_with_id));
      LinkList = xml.children('LinkList');
      obj.set('linklist', $a.LinkList.from_xml2(LinkList, deferred, object_with_id));
      DirectionsCache = xml.children('DirectionsCache');
      obj.set('directionscache', $a.DirectionsCache.from_xml2(DirectionsCache, deferred, object_with_id));
      IntersectionCache = xml.children('IntersectionCache');
      obj.set('intersectioncache', $a.IntersectionCache.from_xml2(IntersectionCache, deferred, object_with_id));
      name = $(xml).attr('name');
      obj.set('name', name);
      dt = $(xml).attr('dt');
      obj.set('dt', Number(dt));
      id = $(xml).attr('id');
      obj.set('id', id);
      if (obj.resolve_references) {
        obj.resolve_references(deferred, object_with_id);
      }
      return obj;
    };

    Network.prototype.to_xml = function(doc) {
      var xml;
      xml = doc.createElement('network');
      if (this.encode_references) {
        this.encode_references();
      }
      if (this.has('description')) {
        xml.appendChild(this.get('description').to_xml(doc));
      }
      if (this.has('position')) {
        xml.appendChild(this.get('position').to_xml(doc));
      }
      if (this.has('nodelist')) {
        xml.appendChild(this.get('nodelist').to_xml(doc));
      }
      if (this.has('linklist')) {
        xml.appendChild(this.get('linklist').to_xml(doc));
      }
      if (this.has('directionscache')) {
        xml.appendChild(this.get('directionscache').to_xml(doc));
      }
      if (this.has('intersectioncache')) {
        xml.appendChild(this.get('intersectioncache').to_xml(doc));
      }
      if (this.has('name')) {
        xml.setAttribute('name', this.get('name'));
      }
      if (this.has('dt')) {
        xml.setAttribute('dt', this.get('dt'));
      }
      if (this.has('id')) {
        xml.setAttribute('id', this.get('id'));
      }
      return xml;
    };

    Network.prototype.deep_copy = function() {
      return Network.from_xml1(this.to_xml(), {});
    };

    Network.prototype.inspect = function(depth, indent, orig_depth) {
      if (depth == null) {
        depth = 1;
      }
      if (indent == null) {
        indent = false;
      }
      if (orig_depth == null) {
        orig_depth = -1;
      }
      return null;
    };

    Network.prototype.make_tree = function() {
      return null;
    };

    return Network;

  })(Backbone.Model);

}).call(this);
