// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.sirius.NodeCollection = (function(_super) {
    var $a;

    __extends(NodeCollection, _super);

    function NodeCollection() {
      return NodeCollection.__super__.constructor.apply(this, arguments);
    }

    $a = window.sirius;

    NodeCollection.prototype.model = $a.Node;

    NodeCollection.prototype.initialize = function(models) {
      this.models = models;
      return this.models.forEach(function(node) {
        return node.set('selected', false);
      });
    };

    NodeCollection.prototype.getBrowserColumnData = function() {
      return this.models.map(function(node) {
        return [node.get('id'), node.get('name'), node.get('type')];
      });
    };

    NodeCollection.prototype.setSelected = function(nodes) {
      return _.each(nodes, function(node) {
        if (!node.get('selected')) {
          return node.set('selected', true);
        }
      });
    };

    return NodeCollection;

  })(Backbone.Collection);

}).call(this);
