// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.sirius.Od = (function(_super) {
    var $a;

    __extends(Od, _super);

    /* $a = alias for sirius namespace
    */


    function Od() {
      return Od.__super__.constructor.apply(this, arguments);
    }

    $a = window.sirius;

    Od.from_xml1 = function(xml, object_with_id) {
      var deferred, fn, obj, _i, _len;
      deferred = [];
      obj = this.from_xml2(xml, deferred, object_with_id);
      for (_i = 0, _len = deferred.length; _i < _len; _i++) {
        fn = deferred[_i];
        fn();
      }
      return obj;
    };

    Od.from_xml2 = function(xml, deferred, object_with_id) {
      var decision_points, id, link_id_destination, link_id_origin, obj, route_segments;
      if (!(xml != null) || xml.length === 0) {
        return null;
      }
      obj = new window.sirius.Od();
      route_segments = xml.children('route_segments');
      obj.set('route_segments', $a.Route_segments.from_xml2(route_segments, deferred, object_with_id));
      decision_points = xml.children('decision_points');
      obj.set('decision_points', $a.Decision_points.from_xml2(decision_points, deferred, object_with_id));
      id = $(xml).attr('id');
      obj.set('id', id);
      link_id_origin = $(xml).attr('link_id_origin');
      obj.set('link_id_origin', link_id_origin);
      link_id_destination = $(xml).attr('link_id_destination');
      obj.set('link_id_destination', link_id_destination);
      if (object_with_id.od) {
        object_with_id.od[obj.id] = obj;
      }
      if (obj.resolve_references) {
        obj.resolve_references(deferred, object_with_id);
      }
      return obj;
    };

    Od.prototype.to_xml = function(doc) {
      var xml;
      xml = doc.createElement('od');
      if (this.encode_references) {
        this.encode_references();
      }
      if (this.has('route_segments')) {
        xml.appendChild(this.get('route_segments').to_xml(doc));
      }
      if (this.has('decision_points')) {
        xml.appendChild(this.get('decision_points').to_xml(doc));
      }
      if (this.has('id')) {
        xml.setAttribute('id', this.get('id'));
      }
      if (this.has('link_id_origin')) {
        xml.setAttribute('link_id_origin', this.get('link_id_origin'));
      }
      if (this.has('link_id_destination')) {
        xml.setAttribute('link_id_destination', this.get('link_id_destination'));
      }
      return xml;
    };

    Od.prototype.deep_copy = function() {
      return Od.from_xml1(this.to_xml(), {});
    };

    Od.prototype.inspect = function(depth, indent, orig_depth) {
      if (depth == null) {
        depth = 1;
      }
      if (indent == null) {
        indent = false;
      }
      if (orig_depth == null) {
        orig_depth = -1;
      }
      return null;
    };

    Od.prototype.make_tree = function() {
      return null;
    };

    return Od;

  })(Backbone.Model);

}).call(this);
