// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.sirius.ODDemandProfileSet = (function(_super) {
    var $a;

    __extends(ODDemandProfileSet, _super);

    /* $a = alias for sirius namespace
    */


    function ODDemandProfileSet() {
      return ODDemandProfileSet.__super__.constructor.apply(this, arguments);
    }

    $a = window.sirius;

    ODDemandProfileSet.from_xml1 = function(xml, object_with_id) {
      var deferred, fn, obj, _i, _len;
      deferred = [];
      obj = this.from_xml2(xml, deferred, object_with_id);
      for (_i = 0, _len = deferred.length; _i < _len; _i++) {
        fn = deferred[_i];
        fn();
      }
      return obj;
    };

    ODDemandProfileSet.from_xml2 = function(xml, deferred, object_with_id) {
      var VehicleTypeOrder, description, id, name, obj, od_demandProfile;
      if (!(xml != null) || xml.length === 0) {
        return null;
      }
      obj = new window.sirius.ODDemandProfileSet();
      description = xml.children('description');
      obj.set('description', $a.Description.from_xml2(description, deferred, object_with_id));
      VehicleTypeOrder = xml.children('VehicleTypeOrder');
      obj.set('vehicletypeorder', $a.VehicleTypeOrder.from_xml2(VehicleTypeOrder, deferred, object_with_id));
      od_demandProfile = xml.children('od_demandProfile');
      obj.set('od_demandprofile', _.map($(od_demandProfile), function(od_demandProfile_i) {
        return $a.Od_demandProfile.from_xml2($(od_demandProfile_i), deferred, object_with_id);
      }));
      id = $(xml).attr('id');
      obj.set('id', id);
      name = $(xml).attr('name');
      obj.set('name', name);
      if (obj.resolve_references) {
        obj.resolve_references(deferred, object_with_id);
      }
      return obj;
    };

    ODDemandProfileSet.prototype.to_xml = function(doc) {
      var xml;
      xml = doc.createElement('ODDemandProfileSet');
      if (this.encode_references) {
        this.encode_references();
      }
      if (this.has('description')) {
        xml.appendChild(this.get('description').to_xml(doc));
      }
      if (this.has('vehicletypeorder')) {
        xml.appendChild(this.get('vehicletypeorder').to_xml(doc));
      }
      _.each(this.get('od_demandprofile') || [], function(a_od_demandprofile) {
        return xml.appendChild(a_od_demandprofile.to_xml(doc));
      });
      if (this.has('id') && this.id !== "") {
        xml.setAttribute('id', this.get('id'));
      }
      if (this.has('name') && this.name !== "") {
        xml.setAttribute('name', this.get('name'));
      }
      return xml;
    };

    ODDemandProfileSet.prototype.deep_copy = function() {
      return ODDemandProfileSet.from_xml1(this.to_xml(), {});
    };

    ODDemandProfileSet.prototype.inspect = function(depth, indent, orig_depth) {
      if (depth == null) {
        depth = 1;
      }
      if (indent == null) {
        indent = false;
      }
      if (orig_depth == null) {
        orig_depth = -1;
      }
      return null;
    };

    ODDemandProfileSet.prototype.make_tree = function() {
      return null;
    };

    return ODDemandProfileSet;

  })(Backbone.Model);

}).call(this);
