// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.sirius.ODList = (function(_super) {
    var $a;

    __extends(ODList, _super);

    /* $a = alias for sirius namespace
    */


    function ODList() {
      return ODList.__super__.constructor.apply(this, arguments);
    }

    $a = window.sirius;

    ODList.from_xml1 = function(xml, object_with_id) {
      var deferred, fn, obj, _i, _len;
      deferred = [];
      obj = this.from_xml2(xml, deferred, object_with_id);
      for (_i = 0, _len = deferred.length; _i < _len; _i++) {
        fn = deferred[_i];
        fn();
      }
      return obj;
    };

    ODList.from_xml2 = function(xml, deferred, object_with_id) {
      var id, name, obj, od;
      if (!(xml != null) || xml.length === 0) {
        return null;
      }
      obj = new window.sirius.ODList();
      od = xml.children('od');
      obj.set('od', _.map($(od), function(od_i) {
        return $a.Od.from_xml2($(od_i), deferred, object_with_id);
      }));
      id = $(xml).attr('id');
      obj.set('id', id);
      name = $(xml).attr('name');
      obj.set('name', name);
      if (obj.resolve_references) {
        obj.resolve_references(deferred, object_with_id);
      }
      return obj;
    };

    ODList.prototype.to_xml = function(doc) {
      var xml;
      xml = doc.createElement('ODList');
      if (this.encode_references) {
        this.encode_references();
      }
      _.each(this.get('od') || [], function(a_od) {
        return xml.appendChild(a_od.to_xml(doc));
      });
      if (this.has('id') && this.id !== "") {
        xml.setAttribute('id', this.get('id'));
      }
      if (this.has('name') && this.name !== "") {
        xml.setAttribute('name', this.get('name'));
      }
      return xml;
    };

    ODList.prototype.deep_copy = function() {
      return ODList.from_xml1(this.to_xml(), {});
    };

    ODList.prototype.inspect = function(depth, indent, orig_depth) {
      if (depth == null) {
        depth = 1;
      }
      if (indent == null) {
        indent = false;
      }
      if (orig_depth == null) {
        orig_depth = -1;
      }
      return null;
    };

    ODList.prototype.make_tree = function() {
      return null;
    };

    return ODList;

  })(Backbone.Model);

}).call(this);
