// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.sirius.On_off_switch = (function(_super) {
    var $a;

    __extends(On_off_switch, _super);

    /* $a = alias for sirius namespace
    */


    function On_off_switch() {
      return On_off_switch.__super__.constructor.apply(this, arguments);
    }

    $a = window.sirius;

    On_off_switch.from_xml1 = function(xml, object_with_id) {
      var deferred, fn, obj, _i, _len;
      deferred = [];
      obj = this.from_xml2(xml, deferred, object_with_id);
      for (_i = 0, _len = deferred.length; _i < _len; _i++) {
        fn = deferred[_i];
        fn();
      }
      return obj;
    };

    On_off_switch.from_xml2 = function(xml, deferred, object_with_id) {
      var obj, value;
      if (!(xml != null) || xml.length === 0) {
        return null;
      }
      obj = new window.sirius.On_off_switch();
      value = $(xml).attr('value');
      obj.set('value', value);
      if (obj.resolve_references) {
        obj.resolve_references(deferred, object_with_id);
      }
      return obj;
    };

    On_off_switch.prototype.to_xml = function(doc) {
      var xml;
      xml = doc.createElement('on_off_switch');
      if (this.encode_references) {
        this.encode_references();
      }
      if (this.has('value')) {
        xml.setAttribute('value', this.get('value'));
      }
      return xml;
    };

    On_off_switch.prototype.deep_copy = function() {
      return On_off_switch.from_xml1(this.to_xml(), {});
    };

    On_off_switch.prototype.inspect = function(depth, indent, orig_depth) {
      if (depth == null) {
        depth = 1;
      }
      if (indent == null) {
        indent = false;
      }
      if (orig_depth == null) {
        orig_depth = -1;
      }
      return null;
    };

    On_off_switch.prototype.make_tree = function() {
      return null;
    };

    return On_off_switch;

  })(Backbone.Model);

}).call(this);
