// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.sirius.Plan_reference = (function(_super) {
    var $a;

    __extends(Plan_reference, _super);

    /* $a = alias for sirius namespace
    */


    function Plan_reference() {
      return Plan_reference.__super__.constructor.apply(this, arguments);
    }

    $a = window.sirius;

    Plan_reference.from_xml1 = function(xml, object_with_id) {
      var deferred, fn, obj, _i, _len;
      deferred = [];
      obj = this.from_xml2(xml, deferred, object_with_id);
      for (_i = 0, _len = deferred.length; _i < _len; _i++) {
        fn = deferred[_i];
        fn();
      }
      return obj;
    };

    Plan_reference.from_xml2 = function(xml, deferred, object_with_id) {
      var obj, plan_id, start_time;
      if (!(xml != null) || xml.length === 0) {
        return null;
      }
      obj = new window.sirius.Plan_reference();
      plan_id = $(xml).attr('plan_id');
      obj.set('plan_id', plan_id);
      start_time = $(xml).attr('start_time');
      obj.set('start_time', Number(start_time));
      if (obj.resolve_references) {
        obj.resolve_references(deferred, object_with_id);
      }
      return obj;
    };

    Plan_reference.prototype.to_xml = function(doc) {
      var xml;
      xml = doc.createElement('plan_reference');
      if (this.encode_references) {
        this.encode_references();
      }
      if (this.has('plan_id')) {
        xml.setAttribute('plan_id', this.get('plan_id'));
      }
      if (this.has('start_time')) {
        xml.setAttribute('start_time', this.get('start_time'));
      }
      return xml;
    };

    Plan_reference.prototype.deep_copy = function() {
      return Plan_reference.from_xml1(this.to_xml(), {});
    };

    Plan_reference.prototype.inspect = function(depth, indent, orig_depth) {
      if (depth == null) {
        depth = 1;
      }
      if (indent == null) {
        indent = false;
      }
      if (orig_depth == null) {
        orig_depth = -1;
      }
      return null;
    };

    Plan_reference.prototype.make_tree = function() {
      return null;
    };

    return Plan_reference;

  })(Backbone.Model);

}).call(this);
