// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.sirius.PlanSequence = (function(_super) {
    var $a;

    __extends(PlanSequence, _super);

    /* $a = alias for sirius namespace
    */


    function PlanSequence() {
      return PlanSequence.__super__.constructor.apply(this, arguments);
    }

    $a = window.sirius;

    PlanSequence.from_xml1 = function(xml, object_with_id) {
      var deferred, fn, obj, _i, _len;
      deferred = [];
      obj = this.from_xml2(xml, deferred, object_with_id);
      for (_i = 0, _len = deferred.length; _i < _len; _i++) {
        fn = deferred[_i];
        fn();
      }
      return obj;
    };

    PlanSequence.from_xml2 = function(xml, deferred, object_with_id) {
      var obj, plan_reference, transition_delay;
      if (!(xml != null) || xml.length === 0) {
        return null;
      }
      obj = new window.sirius.PlanSequence();
      plan_reference = xml.children('plan_reference');
      obj.set('plan_reference', _.map($(plan_reference), function(plan_reference_i) {
        return $a.Plan_reference.from_xml2($(plan_reference_i), deferred, object_with_id);
      }));
      transition_delay = $(xml).attr('transition_delay');
      obj.set('transition_delay', Number(transition_delay));
      if (obj.resolve_references) {
        obj.resolve_references(deferred, object_with_id);
      }
      return obj;
    };

    PlanSequence.prototype.to_xml = function(doc) {
      var xml;
      xml = doc.createElement('PlanSequence');
      if (this.encode_references) {
        this.encode_references();
      }
      _.each(this.get('plan_reference') || [], function(a_plan_reference) {
        return xml.appendChild(a_plan_reference.to_xml(doc));
      });
      if (this.has('transition_delay')) {
        xml.setAttribute('transition_delay', this.get('transition_delay'));
      }
      return xml;
    };

    PlanSequence.prototype.deep_copy = function() {
      return PlanSequence.from_xml1(this.to_xml(), {});
    };

    PlanSequence.prototype.inspect = function(depth, indent, orig_depth) {
      if (depth == null) {
        depth = 1;
      }
      if (indent == null) {
        indent = false;
      }
      if (orig_depth == null) {
        orig_depth = -1;
      }
      return null;
    };

    PlanSequence.prototype.make_tree = function() {
      return null;
    };

    return PlanSequence;

  })(Backbone.Model);

}).call(this);
