// Generated by CoffeeScript 1.3.3
(function() {

  window.sirius.ReferenceHelper = {
    resolver: function(fieldGet, fieldSet, fieldType, name, errName, applyToChild) {
      return function(deferred, object_with_id) {
        var _this = this;
        return deferred.push(function() {
          var idVal, result;
          idVal = _this.get(fieldGet);
          result = object_with_id[fieldType][idVal];
          if (!result) {
            throw "" + errName + " instance can't find " + fieldType + " for obj id == " + idVal;
          }
          _this.set(fieldType, result);
          if (applyToChild) {
            return result.set(name, _this);
          }
        });
      };
    }
  };

}).call(this);
