// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.sirius.Route_segment = (function(_super) {
    var $a;

    __extends(Route_segment, _super);

    /* $a = alias for sirius namespace
    */


    function Route_segment() {
      return Route_segment.__super__.constructor.apply(this, arguments);
    }

    $a = window.sirius;

    Route_segment.from_xml1 = function(xml, object_with_id) {
      var deferred, fn, obj, _i, _len;
      deferred = [];
      obj = this.from_xml2(xml, deferred, object_with_id);
      for (_i = 0, _len = deferred.length; _i < _len; _i++) {
        fn = deferred[_i];
        fn();
      }
      return obj;
    };

    Route_segment.from_xml2 = function(xml, deferred, object_with_id) {
      var id, links, obj;
      if (!(xml != null) || xml.length === 0) {
        return null;
      }
      obj = new window.sirius.Route_segment();
      links = xml.children('links');
      obj.set('links', _.map($(links), function(links_i) {
        return $a.Links.from_xml2($(links_i), deferred, object_with_id);
      }));
      id = $(xml).attr('id');
      obj.set('id', id);
      if (obj.resolve_references) {
        obj.resolve_references(deferred, object_with_id);
      }
      return obj;
    };

    Route_segment.prototype.to_xml = function(doc) {
      var xml;
      xml = doc.createElement('route_segment');
      if (this.encode_references) {
        this.encode_references();
      }
      _.each(this.get('links') || [], function(a_links) {
        return xml.appendChild(a_links.to_xml(doc));
      });
      if (this.has('id')) {
        xml.setAttribute('id', this.get('id'));
      }
      return xml;
    };

    Route_segment.prototype.deep_copy = function() {
      return Route_segment.from_xml1(this.to_xml(), {});
    };

    Route_segment.prototype.inspect = function(depth, indent, orig_depth) {
      if (depth == null) {
        depth = 1;
      }
      if (indent == null) {
        indent = false;
      }
      if (orig_depth == null) {
        orig_depth = -1;
      }
      return null;
    };

    Route_segment.prototype.make_tree = function() {
      return null;
    };

    return Route_segment;

  })(Backbone.Model);

}).call(this);
