// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.sirius.RouteSegments = (function(_super) {
    var $a;

    __extends(RouteSegments, _super);

    /* $a = alias for sirius namespace
    */


    function RouteSegments() {
      return RouteSegments.__super__.constructor.apply(this, arguments);
    }

    $a = window.sirius;

    RouteSegments.from_xml1 = function(xml, object_with_id) {
      var deferred, fn, obj, _i, _len;
      deferred = [];
      obj = this.from_xml2(xml, deferred, object_with_id);
      for (_i = 0, _len = deferred.length; _i < _len; _i++) {
        fn = deferred[_i];
        fn();
      }
      return obj;
    };

    RouteSegments.from_xml2 = function(xml, deferred, object_with_id) {
      var obj, route_segment;
      if (!(xml != null) || xml.length === 0) {
        return null;
      }
      obj = new window.sirius.RouteSegments();
      route_segment = xml.children('route_segment');
      obj.set('route_segment', _.map($(route_segment), function(route_segment_i) {
        return $a.Route_segment.from_xml2($(route_segment_i), deferred, object_with_id);
      }));
      if (obj.resolve_references) {
        obj.resolve_references(deferred, object_with_id);
      }
      return obj;
    };

    RouteSegments.prototype.to_xml = function(doc) {
      var xml;
      xml = doc.createElement('RouteSegments');
      if (this.encode_references) {
        this.encode_references();
      }
      _.each(this.get('route_segment') || [], function(a_route_segment) {
        return xml.appendChild(a_route_segment.to_xml(doc));
      });
      return xml;
    };

    RouteSegments.prototype.deep_copy = function() {
      return RouteSegments.from_xml1(this.to_xml(), {});
    };

    RouteSegments.prototype.inspect = function(depth, indent, orig_depth) {
      if (depth == null) {
        depth = 1;
      }
      if (indent == null) {
        indent = false;
      }
      if (orig_depth == null) {
        orig_depth = -1;
      }
      return null;
    };

    RouteSegments.prototype.make_tree = function() {
      return null;
    };

    return RouteSegments;

  })(Backbone.Model);

}).call(this);
