// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.sirius.ScenarioElement = (function(_super) {
    var $a;

    __extends(ScenarioElement, _super);

    /* $a = alias for sirius namespace
    */


    function ScenarioElement() {
      return ScenarioElement.__super__.constructor.apply(this, arguments);
    }

    $a = window.sirius;

    ScenarioElement.from_xml1 = function(xml, object_with_id) {
      var deferred, fn, obj, _i, _len;
      deferred = [];
      obj = this.from_xml2(xml, deferred, object_with_id);
      for (_i = 0, _len = deferred.length; _i < _len; _i++) {
        fn = deferred[_i];
        fn();
      }
      return obj;
    };

    ScenarioElement.from_xml2 = function(xml, deferred, object_with_id) {
      var id, obj, type, usage;
      if (!(xml != null) || xml.length === 0) {
        return null;
      }
      obj = new window.sirius.ScenarioElement();
      type = $(xml).attr('type');
      obj.set('type', type);
      id = $(xml).attr('id');
      obj.set('id', id);
      usage = $(xml).attr('usage');
      obj.set('usage', usage);
      if (obj.resolve_references) {
        obj.resolve_references(deferred, object_with_id);
      }
      return obj;
    };

    ScenarioElement.prototype.to_xml = function(doc) {
      var xml;
      xml = doc.createElement('scenarioElement');
      if (this.encode_references) {
        this.encode_references();
      }
      if (this.has('type')) {
        xml.setAttribute('type', this.get('type'));
      }
      if (this.has('id')) {
        xml.setAttribute('id', this.get('id'));
      }
      if (this.has('usage')) {
        xml.setAttribute('usage', this.get('usage'));
      }
      return xml;
    };

    ScenarioElement.prototype.deep_copy = function() {
      return ScenarioElement.from_xml1(this.to_xml(), {});
    };

    ScenarioElement.prototype.inspect = function(depth, indent, orig_depth) {
      if (depth == null) {
        depth = 1;
      }
      if (indent == null) {
        indent = false;
      }
      if (orig_depth == null) {
        orig_depth = -1;
      }
      return null;
    };

    ScenarioElement.prototype.make_tree = function() {
      return null;
    };

    return ScenarioElement;

  })(Backbone.Model);

}).call(this);
