// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.sirius.Sensor = (function(_super) {
    var $a;

    __extends(Sensor, _super);

    /* $a = alias for sirius namespace
    */


    function Sensor() {
      return Sensor.__super__.constructor.apply(this, arguments);
    }

    $a = window.sirius;

    Sensor.from_xml1 = function(xml, object_with_id) {
      var deferred, fn, obj, _i, _len;
      deferred = [];
      obj = this.from_xml2(xml, deferred, object_with_id);
      for (_i = 0, _len = deferred.length; _i < _len; _i++) {
        fn = deferred[_i];
        fn();
      }
      return obj;
    };

    Sensor.from_xml2 = function(xml, deferred, object_with_id) {
      var data_sources, description, display_position, id, link_position, link_reference, link_type, obj, parameters, position, type;
      if (!(xml != null) || xml.length === 0) {
        return null;
      }
      obj = new window.sirius.Sensor();
      description = xml.children('description');
      obj.set('description', $a.Description.from_xml2(description, deferred, object_with_id));
      position = xml.children('position');
      obj.set('position', $a.Position.from_xml2(position, deferred, object_with_id));
      display_position = xml.children('display_position');
      obj.set('display_position', $a.Display_position.from_xml2(display_position, deferred, object_with_id));
      link_reference = xml.children('link_reference');
      obj.set('link_reference', $a.Link_reference.from_xml2(link_reference, deferred, object_with_id));
      parameters = xml.children('parameters');
      obj.set('parameters', _.reduce(parameters.find("parameter"), function(acc, par_xml) {
        var wrapped_xml;
        wrapped_xml = $(par_xml);
        acc[wrapped_xml.attr('name')] = wrapped_xml.attr('value');
        return acc;
      }, {}));
      data_sources = xml.children('data_sources');
      obj.set('data_sources', $a.Data_sources.from_xml2(data_sources, deferred, object_with_id));
      id = $(xml).attr('id');
      obj.set('id', id);
      link_position = $(xml).attr('link_position');
      obj.set('link_position', Number(link_position));
      type = $(xml).attr('type');
      obj.set('type', type);
      link_type = $(xml).attr('link_type');
      obj.set('link_type', link_type);
      if (obj.resolve_references) {
        obj.resolve_references(deferred, object_with_id);
      }
      return obj;
    };

    Sensor.prototype.to_xml = function(doc) {
      var parameters_xml, xml;
      xml = doc.createElement('sensor');
      if (this.encode_references) {
        this.encode_references();
      }
      if (this.has('description')) {
        xml.appendChild(this.get('description').to_xml(doc));
      }
      if (this.has('position')) {
        xml.appendChild(this.get('position').to_xml(doc));
      }
      if (this.has('display_position')) {
        xml.appendChild(this.get('display_position').to_xml(doc));
      }
      if (this.has('link_reference')) {
        xml.appendChild(this.get('link_reference').to_xml(doc));
      }
      if (this.has('parameters')) {
        parameters_xml = doc.createElement('parameters');
        _.each(this.get('parameters'), function(par_val, par_name) {
          var parameter_xml;
          parameter_xml = doc.createElement('parameter');
          parameter_xml.setAttribute(par_name, par_val);
          return parameters_xml.appendChild(parameter_xml);
        });
        xml.appendChild(parameters_xml);
      }
      if (this.has('data_sources')) {
        xml.appendChild(this.get('data_sources').to_xml(doc));
      }
      if (this.has('id')) {
        xml.setAttribute('id', this.get('id'));
      }
      if (this.has('link_position')) {
        xml.setAttribute('link_position', this.get('link_position'));
      }
      if (this.has('type')) {
        xml.setAttribute('type', this.get('type'));
      }
      if (this.has('link_type')) {
        xml.setAttribute('link_type', this.get('link_type'));
      }
      return xml;
    };

    Sensor.prototype.deep_copy = function() {
      return Sensor.from_xml1(this.to_xml(), {});
    };

    Sensor.prototype.inspect = function(depth, indent, orig_depth) {
      if (depth == null) {
        depth = 1;
      }
      if (indent == null) {
        indent = false;
      }
      if (orig_depth == null) {
        orig_depth = -1;
      }
      return null;
    };

    Sensor.prototype.make_tree = function() {
      return null;
    };

    return Sensor;

  })(Backbone.Model);

}).call(this);
