// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.sirius.Settings = (function(_super) {
    var $a;

    __extends(Settings, _super);

    /* $a = alias for sirius namespace
    */


    function Settings() {
      return Settings.__super__.constructor.apply(this, arguments);
    }

    $a = window.sirius;

    Settings.from_xml1 = function(xml, object_with_id) {
      var deferred, fn, obj, _i, _len;
      deferred = [];
      obj = this.from_xml2(xml, deferred, object_with_id);
      for (_i = 0, _len = deferred.length; _i < _len; _i++) {
        fn = deferred[_i];
        fn();
      }
      return obj;
    };

    Settings.from_xml2 = function(xml, deferred, object_with_id) {
      var VehicleTypes, obj, units;
      if (!(xml != null) || xml.length === 0) {
        return null;
      }
      obj = new window.sirius.Settings();
      VehicleTypes = xml.children('VehicleTypes');
      obj.set('vehicletypes', $a.VehicleTypes.from_xml2(VehicleTypes, deferred, object_with_id));
      units = xml.children('units');
      obj.set('units', $a.Units.from_xml2(units, deferred, object_with_id));
      if (obj.resolve_references) {
        obj.resolve_references(deferred, object_with_id);
      }
      return obj;
    };

    Settings.prototype.to_xml = function(doc) {
      var xml;
      xml = doc.createElement('settings');
      if (this.encode_references) {
        this.encode_references();
      }
      if (this.has('vehicletypes')) {
        xml.appendChild(this.get('vehicletypes').to_xml(doc));
      }
      if (this.has('units')) {
        xml.appendChild(this.get('units').to_xml(doc));
      }
      return xml;
    };

    Settings.prototype.deep_copy = function() {
      return Settings.from_xml1(this.to_xml(), {});
    };

    Settings.prototype.inspect = function(depth, indent, orig_depth) {
      if (depth == null) {
        depth = 1;
      }
      if (indent == null) {
        indent = false;
      }
      if (orig_depth == null) {
        orig_depth = -1;
      }
      return null;
    };

    Settings.prototype.make_tree = function() {
      return null;
    };

    return Settings;

  })(Backbone.Model);

}).call(this);
