// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.sirius.Signal = (function(_super) {
    var $a;

    __extends(Signal, _super);

    /* $a = alias for sirius namespace
    */


    function Signal() {
      return Signal.__super__.constructor.apply(this, arguments);
    }

    $a = window.sirius;

    Signal.from_xml1 = function(xml, object_with_id) {
      var deferred, fn, obj, _i, _len;
      deferred = [];
      obj = this.from_xml2(xml, deferred, object_with_id);
      for (_i = 0, _len = deferred.length; _i < _len; _i++) {
        fn = deferred[_i];
        fn();
      }
      return obj;
    };

    Signal.from_xml2 = function(xml, deferred, object_with_id) {
      var id, node_id, obj, phase;
      if (!(xml != null) || xml.length === 0) {
        return null;
      }
      obj = new window.sirius.Signal();
      phase = xml.children('phase');
      obj.set('phase', _.map($(phase), function(phase_i) {
        return $a.Phase.from_xml2($(phase_i), deferred, object_with_id);
      }));
      id = $(xml).attr('id');
      obj.set('id', id);
      node_id = $(xml).attr('node_id');
      obj.set('node_id', node_id);
      if (obj.resolve_references) {
        obj.resolve_references(deferred, object_with_id);
      }
      return obj;
    };

    Signal.prototype.to_xml = function(doc) {
      var xml;
      xml = doc.createElement('signal');
      if (this.encode_references) {
        this.encode_references();
      }
      _.each(this.get('phase') || [], function(a_phase) {
        return xml.appendChild(a_phase.to_xml(doc));
      });
      if (this.has('id')) {
        xml.setAttribute('id', this.get('id'));
      }
      if (this.has('node_id')) {
        xml.setAttribute('node_id', this.get('node_id'));
      }
      return xml;
    };

    Signal.prototype.deep_copy = function() {
      return Signal.from_xml1(this.to_xml(), {});
    };

    Signal.prototype.inspect = function(depth, indent, orig_depth) {
      if (depth == null) {
        depth = 1;
      }
      if (indent == null) {
        indent = false;
      }
      if (orig_depth == null) {
        orig_depth = -1;
      }
      return null;
    };

    Signal.prototype.make_tree = function() {
      return null;
    };

    return Signal;

  })(Backbone.Model);

}).call(this);
