// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.sirius.SplitratioEvent = (function(_super) {
    var $a;

    __extends(SplitratioEvent, _super);

    /* $a = alias for sirius namespace
    */


    function SplitratioEvent() {
      return SplitratioEvent.__super__.constructor.apply(this, arguments);
    }

    $a = window.sirius;

    SplitratioEvent.from_xml1 = function(xml, object_with_id) {
      var deferred, fn, obj, _i, _len;
      deferred = [];
      obj = this.from_xml2(xml, deferred, object_with_id);
      for (_i = 0, _len = deferred.length; _i < _len; _i++) {
        fn = deferred[_i];
        fn();
      }
      return obj;
    };

    SplitratioEvent.from_xml2 = function(xml, deferred, object_with_id) {
      var link_in, obj, vehicleTypeName;
      if (!(xml != null) || xml.length === 0) {
        return null;
      }
      obj = new window.sirius.SplitratioEvent();
      link_in = $(xml).attr('link_in');
      obj.set('link_in', link_in);
      vehicleTypeName = $(xml).attr('vehicleTypeName');
      obj.set('vehicleTypeName', vehicleTypeName);
      obj.set('text', xml.text());
      if (obj.resolve_references) {
        obj.resolve_references(deferred, object_with_id);
      }
      return obj;
    };

    SplitratioEvent.prototype.to_xml = function(doc) {
      var xml;
      xml = doc.createElement('splitratioEvent');
      if (this.encode_references) {
        this.encode_references();
      }
      if (this.has('link_in')) {
        xml.setAttribute('link_in', this.get('link_in'));
      }
      if (this.has('vehicleTypeName')) {
        xml.setAttribute('vehicleTypeName', this.get('vehicleTypeName'));
      }
      xml.appendChild(doc.createTextNode($a.ArrayText.emit(this.get('text') || [])));
      return xml;
    };

    SplitratioEvent.prototype.deep_copy = function() {
      return SplitratioEvent.from_xml1(this.to_xml(), {});
    };

    SplitratioEvent.prototype.inspect = function(depth, indent, orig_depth) {
      if (depth == null) {
        depth = 1;
      }
      if (indent == null) {
        indent = false;
      }
      if (orig_depth == null) {
        orig_depth = -1;
      }
      return null;
    };

    SplitratioEvent.prototype.make_tree = function() {
      return null;
    };

    return SplitratioEvent;

  })(Backbone.Model);

}).call(this);
