// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.sirius.SplitratioProfile = (function(_super) {
    var $a;

    __extends(SplitratioProfile, _super);

    /* $a = alias for sirius namespace
    */


    function SplitratioProfile() {
      return SplitratioProfile.__super__.constructor.apply(this, arguments);
    }

    $a = window.sirius;

    SplitratioProfile.from_xml1 = function(xml, object_with_id) {
      var deferred, fn, obj, _i, _len;
      deferred = [];
      obj = this.from_xml2(xml, deferred, object_with_id);
      for (_i = 0, _len = deferred.length; _i < _len; _i++) {
        fn = deferred[_i];
        fn();
      }
      return obj;
    };

    SplitratioProfile.from_xml2 = function(xml, deferred, object_with_id) {
      var dt, node_id, obj, splitratio, start_time;
      if (!(xml != null) || xml.length === 0) {
        return null;
      }
      obj = new window.sirius.SplitratioProfile();
      splitratio = xml.children('splitratio');
      obj.set('splitratio', _.map($(splitratio), function(splitratio_i) {
        return $a.Splitratio.from_xml2($(splitratio_i), deferred, object_with_id);
      }));
      node_id = $(xml).attr('node_id');
      obj.set('node_id', node_id);
      start_time = $(xml).attr('start_time');
      obj.set('start_time', Number(start_time));
      dt = $(xml).attr('dt');
      obj.set('dt', Number(dt));
      if (obj.resolve_references) {
        obj.resolve_references(deferred, object_with_id);
      }
      return obj;
    };

    SplitratioProfile.prototype.to_xml = function(doc) {
      var xml;
      xml = doc.createElement('splitratioProfile');
      if (this.encode_references) {
        this.encode_references();
      }
      _.each(this.get('splitratio') || [], function(a_splitratio) {
        return xml.appendChild(a_splitratio.to_xml(doc));
      });
      if (this.has('node_id')) {
        xml.setAttribute('node_id', this.get('node_id'));
      }
      if (this.has('start_time') && this.start_time !== 0) {
        xml.setAttribute('start_time', this.get('start_time'));
      }
      if (this.has('dt')) {
        xml.setAttribute('dt', this.get('dt'));
      }
      return xml;
    };

    SplitratioProfile.prototype.deep_copy = function() {
      return SplitratioProfile.from_xml1(this.to_xml(), {});
    };

    SplitratioProfile.prototype.inspect = function(depth, indent, orig_depth) {
      if (depth == null) {
        depth = 1;
      }
      if (indent == null) {
        indent = false;
      }
      if (orig_depth == null) {
        orig_depth = -1;
      }
      return null;
    };

    SplitratioProfile.prototype.make_tree = function() {
      return null;
    };

    return SplitratioProfile;

  })(Backbone.Model);

}).call(this);
