// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.sirius.TreeChildItemNetworkView = (function(_super) {
    var $a;

    __extends(TreeChildItemNetworkView, _super);

    function TreeChildItemNetworkView() {
      return TreeChildItemNetworkView.__super__.constructor.apply(this, arguments);
    }

    $a = window.sirius;

    TreeChildItemNetworkView.prototype.manageHighlight = function() {
      if (!$a.SHIFT_DOWN) {
        $a.broker.trigger('map:clear_selected');
      }
      if (!$a.SHIFT_DOWN) {
        $a.broker.trigger('app:tree_remove_highlight');
      }
      if (!this.highlighted) {
        this.highlighted = true;
        $a.broker.trigger("map:select_network:" + this.model.cid);
        return this.highlight();
      } else {
        this.highlighted = false;
        $a.broker.trigger("map:clear_network:" + this.model.cid);
        return this.removeHighlight();
      }
    };

    return TreeChildItemNetworkView;

  })(window.sirius.TreeChildItemView);

}).call(this);
