// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.sirius.VehicleTypes = (function(_super) {
    var $a;

    __extends(VehicleTypes, _super);

    /* $a = alias for sirius namespace
    */


    function VehicleTypes() {
      return VehicleTypes.__super__.constructor.apply(this, arguments);
    }

    $a = window.sirius;

    VehicleTypes.from_xml1 = function(xml, object_with_id) {
      var deferred, fn, obj, _i, _len;
      deferred = [];
      obj = this.from_xml2(xml, deferred, object_with_id);
      for (_i = 0, _len = deferred.length; _i < _len; _i++) {
        fn = deferred[_i];
        fn();
      }
      return obj;
    };

    VehicleTypes.from_xml2 = function(xml, deferred, object_with_id) {
      var obj, vehicle_type;
      if (!(xml != null) || xml.length === 0) {
        return null;
      }
      obj = new window.sirius.VehicleTypes();
      vehicle_type = xml.children('vehicle_type');
      obj.set('vehicle_type', _.map($(vehicle_type), function(vehicle_type_i) {
        return $a.Vehicle_type.from_xml2($(vehicle_type_i), deferred, object_with_id);
      }));
      if (obj.resolve_references) {
        obj.resolve_references(deferred, object_with_id);
      }
      return obj;
    };

    VehicleTypes.prototype.to_xml = function(doc) {
      var xml;
      xml = doc.createElement('VehicleTypes');
      if (this.encode_references) {
        this.encode_references();
      }
      _.each(this.get('vehicle_type') || [], function(a_vehicle_type) {
        return xml.appendChild(a_vehicle_type.to_xml(doc));
      });
      return xml;
    };

    VehicleTypes.prototype.deep_copy = function() {
      return VehicleTypes.from_xml1(this.to_xml(), {});
    };

    VehicleTypes.prototype.inspect = function(depth, indent, orig_depth) {
      if (depth == null) {
        depth = 1;
      }
      if (indent == null) {
        indent = false;
      }
      if (orig_depth == null) {
        orig_depth = -1;
      }
      return null;
    };

    VehicleTypes.prototype.make_tree = function() {
      return null;
    };

    return VehicleTypes;

  })(Backbone.Model);

}).call(this);
