// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.sirius.Vehicle_type = (function(_super) {
    var $a;

    __extends(Vehicle_type, _super);

    /* $a = alias for sirius namespace
    */


    function Vehicle_type() {
      return Vehicle_type.__super__.constructor.apply(this, arguments);
    }

    $a = window.sirius;

    Vehicle_type.from_xml1 = function(xml, object_with_id) {
      var deferred, fn, obj, _i, _len;
      deferred = [];
      obj = this.from_xml2(xml, deferred, object_with_id);
      for (_i = 0, _len = deferred.length; _i < _len; _i++) {
        fn = deferred[_i];
        fn();
      }
      return obj;
    };

    Vehicle_type.from_xml2 = function(xml, deferred, object_with_id) {
      var name, obj, weight;
      if (!(xml != null) || xml.length === 0) {
        return null;
      }
      obj = new window.sirius.Vehicle_type();
      name = $(xml).attr('name');
      obj.set('name', name);
      weight = $(xml).attr('weight');
      obj.set('weight', Number(weight));
      if (obj.resolve_references) {
        obj.resolve_references(deferred, object_with_id);
      }
      return obj;
    };

    Vehicle_type.prototype.to_xml = function(doc) {
      var xml;
      xml = doc.createElement('vehicle_type');
      if (this.encode_references) {
        this.encode_references();
      }
      if (this.has('name')) {
        xml.setAttribute('name', this.get('name'));
      }
      if (this.has('weight')) {
        xml.setAttribute('weight', this.get('weight'));
      }
      return xml;
    };

    Vehicle_type.prototype.deep_copy = function() {
      return Vehicle_type.from_xml1(this.to_xml(), {});
    };

    Vehicle_type.prototype.inspect = function(depth, indent, orig_depth) {
      if (depth == null) {
        depth = 1;
      }
      if (indent == null) {
        indent = false;
      }
      if (orig_depth == null) {
        orig_depth = -1;
      }
      return null;
    };

    Vehicle_type.prototype.make_tree = function() {
      return null;
    };

    return Vehicle_type;

  })(Backbone.Model);

}).call(this);
