watch:
	coffee -o js -c ../lib 
	coffee -o js/collections -c ../lib/collections
	coffee -o js/extensions -c ../lib/extensions
	coffee -o js/models -c ../lib/models
	coffee -o js/util -c ../lib/util
	coffee -o js/views -c ../lib/views
	cp -r ../lib/vendor js/.
all:
	coffee -o js -c ../lib 
	coffee -o js/collections -c ../lib/collections
	coffee -o js/extensions -c ../lib/extensions
	coffee -o js/models -c ../lib/models
	coffee -o js/util -c ../lib/util