watch:
	coffee -o js/models/ -c ../lib/sirius-coffee/
	coffee -o js/models/extensions/ -c ../lib/extensions-coffee/
	coffee -o js/models/util -c ../lib/util-coffee/
	coffee -o js/ --watch coffeescripts/

all:
	coffee -o js/models/ -c ../lib/sirius-coffee/
	coffee -o js/models/extensions/ -c ../lib/extensions-coffee/
	coffee -o js/models/util -c ../lib/util-coffee/
	coffee -o js/ -c coffeescripts/