watch:
	coffee -o js/ -c ../lib/sirius-coffee/
	coffee -o js/extensions/ -c ../lib/extensions-coffee/
	coffee -o js/ -c ../lib/util-coffee/
	coffee -o js/ --watch coffeescripts/

all:
	coffee -o js/ -c ../lib/sirius-coffee/
	coffee -o js/extensions/ -c ../lib/extensions-coffee/
	coffee -o js/ -c ../lib/util-coffee/
	coffee -o js/ -c coffeescripts/