watch:
	coffee -o js/ -c ../libs/sirius-coffee/
	coffee -o js/extensions/ -c ../libs/extensions-coffee/
	coffee -o js/ -c ../libs/util-coffee/
	coffee -o js/ --watch coffeescripts/

all:
	coffee -o js/ -c ../libs/sirius-coffee/
	coffee -o js/extensions/ -c ../libs/extensions-coffee/
	coffee -o js/ -c ../libs/util-coffee/
	coffee -o js/ -c coffeescripts/
