// Generated by CoffeeScript 1.3.3
(function() {

  window.sirius.Begin.prototype.resolve_references = window.sirius.ReferenceHelper.resolver('node_id', 'node', 'node', 'begin', 'Begin', false);

  window.sirius.Begin.prototype.encode_references = function() {
    return this.set('node_id', this.get('node').id);
  };

}).call(this);
