// Generated by CoffeeScript 1.3.3
(function() {

  window.sirius.Density.prototype.resolve_references = window.sirius.ReferenceHelper.resolver('link_id', 'link', 'link', 'density', 'Density', true);

  window.sirius.Density.prototype.encode_references = function() {
    return this.set('link_id', this.get('link').id);
  };

}).call(this);
