// Generated by CoffeeScript 1.3.3
(function() {

  window.sirius.End.prototype.resolve_references = window.sirius.ReferenceHelper.resolver('node_id', 'node', 'node', 'end', 'End', false);

  window.sirius.End.prototype.encode_references = function() {
    return this.set('node_id', this.get('node').id);
  };

}).call(this);
