// Generated by CoffeeScript 1.3.3
(function() {

  window.sirius.Event.prototype.display_point = function() {
    var display_position, elt_pt, p, pos_elt;
    display_position = this.get('display_position');
    if (!display_position) {
      display_position = new window.sirius.Display_position();
      p = new window.sirius.Point();
      display_position.get('point').push(p);
      pos_elt = null;
      if (this.has('link')) {
        pos_elt = this.get('link').get('begin').get('node');
      } else if (this.has('node')) {
        pos_elt = this.get('node');
      } else if (this.has('network')) {
        pos_elt = this.get('network');
      }
      if (pos_elt) {
        elt_pt = pos_elt.get('position').get('point')[0];
        p.set('lat', elt_pt.get('lat'));
        p.set('lng', elt_pt.get('lng'));
      } else {
        p.set('lat', 0);
        p.set('lng', 0);
      }
      return display_position.get('point')[0];
    }
  };

  window.sirius.Event.prototype.resolve_references = function(deferred, object_with_id) {
    var _this = this;
    return deferred.push(function() {
      _this.set('targetreferences', []);
      return _.each(_this.get('targetelements').get('scenarioelement'), function(e) {
        switch (e.get('type')) {
          case 'link':
            return _this.get('targetreferences').push(object_with_id.link[e.id]);
          case 'node':
            return _this.get('targetreferences').push(object_with_id.node[e.id]);
          case 'controller':
            return _this.get('targetreferences').push(object_with_id.controller[e.id]);
          case 'sensor':
            return _this.get('targetreferences').push(object_with_id.sensor[e.id]);
          case 'event':
            return _this.get('targetreferences').push(object_with_id.event[e.id]);
          case 'signal':
            return _this.get('targetreferences').push(object_with_id.signal[e.id]);
        }
      });
    });
  };

  window.sirius.Event.prototype.encode_references = function() {};

}).call(this);
