// Generated by CoffeeScript 1.3.3
(function() {

  window.sirius.Intersection.prototype.defaults = {
    stage: []
  };

  window.sirius.Intersection.prototype.resolve_references = window.sirius.ReferenceHelper.resolver('node_id', 'node', 'node', 'intersection', 'Intersection', false);

  window.sirius.Intersection.prototype.encode_references = function() {
    return this.set('node_id', this.get('node').id);
  };

}).call(this);
