// Generated by CoffeeScript 1.3.3
(function() {

  window.sirius.Link.prototype.defaults = {
    type: 'ST',
    lanes: 1,
    lane_offset: 0,
    record: true
  };

  window.sirius.Link.prototype.initialize = function() {
    return this.set('dynamics', new window.sirius.Dynamics());
  };

  window.sirius.Link.prototype.parallel_links = function() {
    var begin_node, end_node,
      _this = this;
    begin_node = this.get('begin').get('node');
    end_node = this.get('end').get('node');
    return _.map(_.filter(begin_node.get('outputs').get('output'), function(output) {
      var link2;
      link2 = output.get('link');
      return link2 !== _this && link2.get('end').get('node') === end_node;
    }), function(output) {
      return output.get('link');
    });
  };

}).call(this);
