// Generated by CoffeeScript 1.3.3
(function() {

  window.sirius.Network.prototype.defaults = {
    ml_control: false,
    q_control: false,
    dt: 300
  };

  window.sirius.Network.prototype.initialize = function() {
    this.set('nodelist', new window.sirius.NodeList);
    this.set('linklist', new window.sirius.LinkList);
    this.set('networklist', new window.sirius.NetworkList);
    this.set('odlist', new window.sirius.ODList);
    this.set('sensorlist', new window.sirius.SensorList);
    this.set('signallist', new window.sirius.SignalList);
    this.set('description', new window.sirius.Description);
    this.set('position', new window.sirius.Position);
    return this.get('position').get('point').push(new window.sirius.Point);
  };

  window.sirius.Network.prototype.description_text = function() {
    return this.get('description').get('text');
  };

  window.sirius.Network.prototype.set_description_text = function(s) {
    return this.get('description').set('text', s);
  };

}).call(this);
