// Generated by CoffeeScript 1.3.3
(function() {

  window.sirius.Node.prototype.input_indexes = function(other_node) {
    return _.map(this.get('inputs').get('input'), function(input, idx) {
      var link;
      link = input.get('link');
      if (link.get('begin').get('node') === other_node) {
        return [link, idx];
      }
    });
  };

  window.sirius.Node.prototype.output_indexes = function(other_node) {
    return _.map(this.get('outputs').get('output'), function(output, idx) {
      var link;
      link = output.get('link');
      if (link.get('end').get('node') === other_node) {
        return [link, idx];
      }
    });
  };

  window.sirius.Node.prototype.terminal = function() {
    return this.get('type') === 'T';
  };

  window.sirius.Node.prototype.signalized = function() {
    return this.get('type') === 'S';
  };

  window.sirius.Node.prototype.inputs = function() {
    return this.get('inputs').get('input');
  };

  window.sirius.Node.prototype.outputs = function() {
    return this.get('outputs').get('output');
  };

  window.sirius.Node.prototype.ios = function() {
    return _.union(this.outputs(), this.inputs());
  };

}).call(this);
