// Generated by CoffeeScript 1.3.3
(function() {

  window.sirius.Od.prototype.initialize = function() {};

  window.sirius.Od.prototype.resolve_references = function(deferred, object_with_id) {
    var _this = this;
    return deferred.push(function() {
      var begin, begin_node, end, end_node, _ref, _ref1;
      _ref = [_this.get('begin'), _this.get('end')], begin = _ref[0], end = _ref[1];
      _ref1 = [object_with_id.node[begin], object_with_id.node[end]], begin_node = _ref1[0], end_node = _ref1[1];
      _this.set('begin_node', begin_node);
      _this.set('end_node', end_node);
      if (!begin_node) {
        throw "Od instance can't find node for id == " + begin;
      }
      if (!end_node) {
        throw "Od instance can't find node for id == " + end;
      }
    });
  };

  window.sirius.Od.prototype.encode_references = function() {
    this.set('begin', this.get('begin_node').id);
    return this.set('end', this.get('end_node').id);
  };

}).call(this);
