// Generated by CoffeeScript 1.3.3
(function() {

  window.sirius.Output.prototype.resolve_references = window.sirius.ReferenceHelper.resolver('link_id', 'link', 'link', 'output', 'Output', false);

  window.sirius.Output.prototype.encode_references = function() {
    return this.set('link_id', this.get('link').id);
  };

}).call(this);
