// Generated by CoffeeScript 1.3.3
(function() {

  window.sirius.Phase.prototype.defaults = {
    yellow_time: 0,
    red_clear_time: 0,
    min_green_time: 0
  };

  window.sirius.Phase.prototype.initialize = function() {
    return this.set('links', new window.sirius.Links);
  };

}).call(this);
