// Generated by CoffeeScript 1.3.3
(function() {

  window.sirius.Sensor.prototype.resolve_references = function(deferred, object_with_id) {
    var _this = this;
    return deferred.push(function() {
      var link;
      link = object_with_id.link[_this.get('link_reference').get('id')];
      return _this.set('link', link);
    });
  };

  window.sirius.Sensor.prototype.point = function() {
    var p;
    p = this.get('position').get('point');
    if (!p[0]) {
      p.push(new Point);
    }
    return p[0];
  };

  window.sirius.Sensor.prototype.display_point = function() {
    var p;
    if (this.has('display_position')) {
      p = this.get('display_position').get('point')[0];
      if (!p) {
        p = new window.sirius.Point;
        p.set('lat', this.get('lat'));
        p.set('lng', this.get('lng'));
        this.get('display_position').get('point').push(p);
      }
      p;

    } else {
      this.get('point');
    }
    sensor.set('lat', row.lat);
    sensor.set('lng', row.lng);
    return sensor.set('elevation', 0);
  };

  window.sirius.Sensor.prototype.lat = function() {
    return this.get('point').get('lat');
  };

  window.sirius.Sensor.prototype.lng = function() {
    return this.get('point').get('lng');
  };

  window.sirius.Sensor.prototype.elevation = function() {
    return this.get('point').get('elevation');
  };

  window.sirius.Sensor.prototype.display_lat = function() {
    return this.display_point().get('lat');
  };

  window.sirius.Sensor.prototype.display_lng = function() {
    return this.display_point().get('lng');
  };

  window.sirius.Sensor.prototype.initialize = function() {
    return this.set('position', new window.sirius.Position);
  };

  window.sirius.Sensor.prototype.defaults = {
    parameters: {}
  };

  window.sirius.Sensor.from_station_row = function(row) {
    var sensor;
    sensor = new window.sirius.Sensor({
      description: new window.sirius.Description({
        text: row.description
      }),
      type: row.type,
      link_type: row.link_type,
      links: null,
      lat: row.lat,
      lng: row.lng,
      elevation: 0,
      display_position: new window.sirius.Display_position()
    });
    if (row.link_type === 'HV') {
      sensor.set('link_type', 'HOV');
    }
    if (row.link_type === 'ML') {
      sensor.set('link_type', 'FW');
    }
    /* TODO set display_position and parameters
    */

    return sensor;
  };

}).call(this);
