// Generated by CoffeeScript 1.3.3
(function() {

  window.sirius.Splitratio.prototype.resolve_references = function(deferred, object_with_id) {
    var _this = this;
    return deferred.push(function() {
      _this.set('in_link', object_with_id.link[_this.get('link_in')]);
      return _this.set('out_link', object_with_id.link[_this.get('link_out')]);
    });
  };

  window.sirius.Splitratio.prototype.encode_references = function() {
    this.set('link_in', this.get('in_link').id);
    return this.set('link_out', this.get('out_link').id);
  };

}).call(this);
